export const ELEMENTS = {

    //login
    campoUsuario: ':nth-child(2) > .form-control',
    campoSenha: ':nth-child(3) > .form-control',
    botaoLogin: '.btn',
    titulo: 'h1',
    abaDemanda: ':nth-child(3) > [href="#"]',
    abaDemandaConsultar: '.menu-open > .treeview-menu > :nth-child(1) > a > span',
    tituloDemanda: 'h1',
    tituloDados: ':nth-child(1) > .box-header > .box-title',
    formRA: '#form_geral > :nth-child(1) > :nth-child(1) > .form-group > .control-label',
    formEmpreendimento: '#form_geral > :nth-child(1) > :nth-child(2) > .form-group > .control-label',
    formPossuiExigencia: '#form_geral > :nth-child(1) > :nth-child(3) > .form-group > label',
    formTipo: '#form_geral > :nth-child(2) > :nth-child(1) > .form-group > .control-label',
    formNumero: '#form_geral > :nth-child(2) > :nth-child(2) > .form-group > .control-label',
    formAno: '#form_geral > :nth-child(2) > :nth-child(3) > .form-group > .control-label',
    labelPossuiReq: ':nth-child(2) > :nth-child(4) > .form-group > label',
    labelOrgaoDemanda: ':nth-child(3) > .col-md-12 > .form-group > .control-label',
    labelDescricao: ':nth-child(4) > .col-md-8 > .form-group > .control-label',
    labelPeriodoData: ':nth-child(5) > :nth-child(1) > :nth-child(1) > :nth-child(1) > .control-label',
    labelPeriodoVig: ':nth-child(5) > :nth-child(2) > :nth-child(1) > .control-label',
    labelStatus: ':nth-child(5) > :nth-child(3) > .form-group > .control-label',
    labelAlerta: '#form_geral > :nth-child(6) > :nth-child(1) > .form-group > .control-label',
    labelPeriodoDias: ':nth-child(6) > :nth-child(3) > .form-group > .control-label',
    labelTitular: ':nth-child(7) > :nth-child(1) > .form-group > label',
    labelSuplente: ':nth-child(7) > :nth-child(2) > .form-group > label',
    labelEmpreenResp: ':nth-child(7) > :nth-child(3) > .form-group > label',
    labelPeriodoRestante: ':nth-child(6) > :nth-child(4) > label',
    formAmbValTotal: '#form_ambiental > :nth-child(1) > :nth-child(1) > :nth-child(1) > label',
    formAmbVR: '#form_ambiental > :nth-child(1) > :nth-child(2) > :nth-child(1) > label',
    formAmbGrauImpacto: '#form_ambiental > :nth-child(1) > :nth-child(3) > :nth-child(1) > label',
    formAmbPrazoLimite: '#form_ambiental > :nth-child(1) > :nth-child(4) > .form-group > label',
    formAmbArquivada: '#form_ambiental > :nth-child(2) > .col-md-2 > .form-group > label',
    formAmbDescricao: ':nth-child(2) > .col-md-10 > .form-group > .control-label',
    formAmbStatusRecurso: '#form_ambiental > :nth-child(3) > :nth-child(1) > .form-group > .control-label',
    formAmbDataLimite: '#form_ambiental > :nth-child(3) > :nth-child(2) > :nth-child(1) > label',
    formAmbDiasRestantes: '#form_ambiental > :nth-child(3) > :nth-child(3) > :nth-child(1) > label',
    formAmbSaldoDevedor: ':nth-child(4) > .col-md-4 > :nth-child(1) > .control-label',

    // Florestal
    formFlorestLegRef: '#form_florestal > :nth-child(1) > :nth-child(1) > .form-group > .control-label',
    formFlorestTipoVeg: '#form_florestal > :nth-child(1) > :nth-child(2) > .form-group > .control-label',
    formFlorestModalPag: '#form_florestal > :nth-child(1) > :nth-child(3) > .form-group > .control-label',
    formFlorestQtdMudasEst: '#form_florestal > :nth-child(2) > :nth-child(1) > :nth-child(1) > label',
    formFlorestQtdMudasDef: '#form_florestal > :nth-child(2) > :nth-child(2) > :nth-child(1) > label',
    formFlorestValorTotal: '#form_florestal > :nth-child(2) > :nth-child(3) > :nth-child(1) > label',
    formFlorestAreaTotal: '#form_florestal > :nth-child(3) > :nth-child(1) > :nth-child(1) > label',
    formFlorestDataLimite: '#form_florestal > :nth-child(3) > :nth-child(2) > :nth-child(1) > label',
    formFlorestDiasRestantes: '#form_florestal > :nth-child(3) > :nth-child(3) > :nth-child(1) > .control-label',
    formFlorestArquivada: ':nth-child(4) > .col-md-2 > .form-group > label',
    formFlorestDescricao: ':nth-child(4) > .col-md-10 > .form-group > .control-label',
    formFlorestStatusRecurso: '#form_florestal > :nth-child(5) > .col-md-4 > .form-group > .control-label',
    formFlorestSaldoDevedor: ':nth-child(6) > .col-md-4 > :nth-child(1) > .control-label',

    // Auto Infração
    formAIDataReceb: '#form_auto_infracao > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > .control-label',
    formAITipoSancao: '#form_auto_infracao > :nth-child(1) > :nth-child(2) > .form-group > .control-label',
    formAIValorMulta: '#form_auto_infracao > :nth-child(1) > :nth-child(3) > :nth-child(1) > label',
    formAITipoAtividade: ':nth-child(1) > :nth-child(4) > .form-group > .control-label',
    formAIOrgaoDescricao: '.col-md-12 > .form-group > .control-label',
    formAIStatus: '#form_auto_infracao > :nth-child(3) > :nth-child(1) > .form-group > .control-label',
    formAIInstancia: ':nth-child(3) > :nth-child(2) > .form-group > .control-label',
    formAIDescricaoStatus: '.col-md-6 > .form-group > .control-label',
    formAITituloPrazos: '.box-title > b',
    formAIPeriodosInstancia: '#form_auto_infracao > :nth-child(5) > .col-md-4 > .form-group > .control-label',
    formAIDataEnvio: ':nth-child(6) > :nth-child(1) > :nth-child(1) > :nth-child(1) > .control-label',
    formAIDataCiencia: ':nth-child(6) > :nth-child(2) > :nth-child(1) > :nth-child(1) > .control-label',
    formAIValorAtual: '#form_auto_infracao > :nth-child(6) > :nth-child(3) > :nth-child(1) > label',
    formAIDataLimiteEnvio: ':nth-child(7) > :nth-child(1) > :nth-child(1) > :nth-child(1) > .control-label',
    formAIDataLimitePagamento: ':nth-child(7) > :nth-child(2) > :nth-child(1) > :nth-child(1) > .control-label'



}
