export const ELEMENTS = {

    //login
    campoUsuario: ':nth-child(2) > .form-control',
    campoSenha: ':nth-child(3) > .form-control',
    botaoLogin: '.btn',
    titulo: 'h1',
    abaDemanda: ':nth-child(3) > [href="#"]',
    abaDemandaConsultar: '.menu-open > .treeview-menu > :nth-child(1) > a > span',
    tituloDemanda: 'h1',
    tituloDados: ':nth-child(1) > .box-header > .box-title',
    formRA: '#form_geral > :nth-child(1) > :nth-child(1) > .form-group > .control-label',
    formEmpreendimento: '#form_geral > :nth-child(1) > :nth-child(2) > .form-group > .control-label',
    formPossuiExigencia: '#form_geral > :nth-child(1) > :nth-child(3) > .form-group > label',
    formTipo: '#form_geral > :nth-child(2) > :nth-child(1) > .form-group > .control-label',
    formNumero: '#form_geral > :nth-child(2) > :nth-child(2) > .form-group > .control-label',
    formAno: '#form_geral > :nth-child(2) > :nth-child(3) > .form-group > .control-label',
    labelPossuiReq: ':nth-child(2) > :nth-child(4) > .form-group > label',
    labelOrgaoDemanda: ':nth-child(3) > .col-md-12 > .form-group > .control-label',
    labelDescricao: ':nth-child(4) > .col-md-8 > .form-group > .control-label',
    labelPeriodoData: ':nth-child(5) > :nth-child(1) > :nth-child(1) > :nth-child(1) > .control-label',
    labelPeriodoVig: ':nth-child(5) > :nth-child(2) > :nth-child(1) > .control-label',
    labelStatus: ':nth-child(5) > :nth-child(3) > .form-group > .control-label',
    labelAlerta: '#form_geral > :nth-child(6) > :nth-child(1) > .form-group > .control-label',
    labelPeriodoDias: ':nth-child(6) > :nth-child(3) > .form-group > .control-label',
    labelTitular: ':nth-child(7) > :nth-child(1) > .form-group > label',
    labelSuplente: ':nth-child(7) > :nth-child(2) > .form-group > label',
    labelEmpreenResp: ':nth-child(7) > :nth-child(3) > .form-group > label',
    labelPeriodoRestante: ':nth-child(6) > :nth-child(4) > label',
    formAmbValTotal: '#form_ambiental > :nth-child(1) > :nth-child(1) > :nth-child(1) > label',
    formAmbVR: '#form_ambiental > :nth-child(1) > :nth-child(2) > :nth-child(1) > label',
    formAmbGrauImpacto: '#form_ambiental > :nth-child(1) > :nth-child(3) > :nth-child(1) > label',
    formAmbPrazoLimite: '#form_ambiental > :nth-child(1) > :nth-child(4) > .form-group > label',
    formAmbArquivada: '#form_ambiental > :nth-child(2) > .col-md-2 > .form-group > label',
    formAmbDescricao: ':nth-child(2) > .col-md-10 > .form-group > .control-label',
    formAmbStatusRecurso: '#form_ambiental > :nth-child(3) > :nth-child(1) > .form-group > .control-label',
    formAmbDataLimite: '#form_ambiental > :nth-child(3) > :nth-child(2) > :nth-child(1) > label',
    formAmbDiasRestantes: '#form_ambiental > :nth-child(3) > :nth-child(3) > :nth-child(1) > label',
    formAmbSaldoDevedor: ':nth-child(4) > .col-md-4 > :nth-child(1) > .control-label',
    // Florestal
    formFlorestLegRef: '#form_florestal > :nth-child(1) > :nth-child(1) > .form-group > .control-label',
    formFlorestTipoVeg: '#form_florestal > :nth-child(1) > :nth-child(2) > .form-group > .control-label',
    formFlorestModalPag: '#form_florestal > :nth-child(1) > :nth-child(3) > .form-group > .control-label',
    formFlorestQtdMudasEst: '#form_florestal > :nth-child(2) > :nth-child(1) > :nth-child(1) > label',
    formFlorestQtdMudasDef: '#form_florestal > :nth-child(2) > :nth-child(2) > :nth-child(1) > label',
    formFlorestValorTotal: '#form_florestal > :nth-child(2) > :nth-child(3) > :nth-child(1) > label',
    formFlorestAreaTotal: '#form_florestal > :nth-child(3) > :nth-child(1) > :nth-child(1) > label',
    formFlorestDataLimite: '#form_florestal > :nth-child(3) > :nth-child(2) > :nth-child(1) > label',
    formFlorestDiasRestantes: '#form_florestal > :nth-child(3) > :nth-child(3) > :nth-child(1) > .control-label',
    formFlorestArquivada: ':nth-child(4) > .col-md-2 > .form-group > label',
    formFlorestDescricao: ':nth-child(4) > .col-md-10 > .form-group > .control-label',
    formFlorestStatusRecurso: '#form_florestal > :nth-child(5) > .col-md-4 > .form-group > .control-label',
    formFlorestSaldoDevedor: ':nth-child(6) > .col-md-4 > :nth-child(1) > .control-label',
    // Auto Infração
    formAIDataReceb: '#form_auto_infracao > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > .control-label',
    formAITipoSancao: '#form_auto_infracao > :nth-child(1) > :nth-child(2) > .form-group > .control-label',
    formAIValorMulta: '#form_auto_infracao > :nth-child(1) > :nth-child(3) > :nth-child(1) > label',
    formAITipoAtividade: ':nth-child(1) > :nth-child(4) > .form-group > .control-label',
    formAIOrgaoDescricao: '.col-md-12 > .form-group > .control-label',
    formAIStatus: '#form_auto_infracao > :nth-child(3) > :nth-child(1) > .form-group > .control-label',
    formAIInstancia: ':nth-child(3) > :nth-child(2) > .form-group > .control-label',
    formAIDescricaoStatus: '.col-md-6 > .form-group > .control-label',
    formAITituloPrazos: '.box-title > b',
    formAIPeriodosInstancia: '#form_auto_infracao > :nth-child(5) > .col-md-4 > .form-group > .control-label',
    formAIDataEnvio: ':nth-child(6) > :nth-child(1) > :nth-child(1) > :nth-child(1) > .control-label',
    formAIDataCiencia: ':nth-child(6) > :nth-child(2) > :nth-child(1) > :nth-child(1) > .control-label',
    formAIValorAtual: '#form_auto_infracao > :nth-child(6) > :nth-child(3) > :nth-child(1) > label',
    formAIDataLimiteEnvio: ':nth-child(7) > :nth-child(1) > :nth-child(1) > :nth-child(1) > .control-label',
    formAIDataLimitePagamento: ':nth-child(7) > :nth-child(2) > :nth-child(1) > :nth-child(1) > .control-label',
    // Tabela Nova Demanda
    tabelaEmpreendimento: '[aria-label="Empreendimento: Ordenar colunas de forma ascendente"]',
    tabelaTipo: '[aria-label="Tipo: Ordenar colunas de forma ascendente"]',
    tabelaNumero: '[aria-label="Nº: Ordenar colunas de forma ascendente"]',
    tabelaAno: '[aria-label="Ano: Ordenar colunas de forma ascendente"]',
    tabelaOrgao: '[aria-label="Órgão: Ordenar colunas de forma ascendente"]',
    tabelaDiasRest: '[aria-label="Dias Rest: Ordenar colunas de forma ascendente"]',
    tabelaAlerta: '[aria-label="Alerta: Ordenar colunas de forma ascendente"]',
    tabelaTitular: '[aria-label="Titular: Ordenar colunas de forma ascendente"]',
    tabelaAcao: '[aria-label="Ação: Ordenar colunas de forma ascendente"]',
    // Título Nova Demanda
    tituloNovaDemanda: '.box-title',
    // Accordions
    accordionDadosGerais: 'div.accordion.float-style:contains("Dados Gerais")',
    accordionDadosCA: 'div.accordion.float-style:contains("Dados Específicos da Compensação Ambiental")',
    accordionDadosCF: 'div.accordion.float-style:contains("Dados Específicos da Compensação Florestal")',
    accordionDadosAI: 'div.accordion.float-style:contains("Dados Específicos do Auto de Infração")',
    // Formulário Específico
    formRA_Especifico: ':nth-child(1) > .col-md-4 > .form-group > .control-label',
    formEmpreendimento_Especifico: ':nth-child(1) > .col-md-6 > .form-group > .control-label',
    formTipo_Especifico: ':nth-child(2) > :nth-child(1) > .form-group > .control-label',
    formNumero_Especifico: ':nth-child(2) > :nth-child(2) > .form-group > .control-label',
    formAno_Especifico: ':nth-child(2) > :nth-child(3) > .form-group > .control-label',
    formOrgaoDemanda_Especifico: ':nth-child(2) > :nth-child(3) > :nth-child(1) > .form-group > .control-label',
    formProcessoSEI_Especifico: ':nth-child(3) > :nth-child(3) > :nth-child(1) > .form-group > label',
    formDataPublicacao_Especifico: ':nth-child(2) > :nth-child(4) > :nth-child(1) > .form-group > .control-label',
    formVigenciaDias_Especifico: ':nth-child(4) > :nth-child(2) > .form-group > .control-label',
    formTitular_Especifico: ':nth-child(2) > :nth-child(6) > :nth-child(1) > .form-group > label',
    formSuplente_Especifico: ':nth-child(2) > :nth-child(6) > :nth-child(2) > .form-group > label',
    formDescricao_Especifico: ':nth-child(5) > .col-md-12 > .form-group > .control-label',
    infoEmpreendimentos: ':nth-child(1) > .col-md-12 > .accordion > b',
    dadosGerais: ':nth-child(1) > :nth-child(1) > :nth-child(2) > .col-md-12 > .accordion > b',
    infoDocumento: ':nth-child(1) > :nth-child(1) > :nth-child(3) > .col-md-12 > .accordion > b',
    associacoesDemanda: '.panel-body > :nth-child(2) > .col-md-12 > .accordion > b',
    compensacaoAmbiental:'.panel-body > :nth-child(3) > .col-md-12 > .accordion',
    compensacaoFlorestal: ':nth-child(4) > .col-md-12 > .accordion',
    autoInfracao: ':nth-child(5) > :nth-child(1) > .accordion',
    whidthTipo: ':nth-child(1) > [whidth="350px"] > b',
    whidthNumero: ':nth-child(2) > [whidth="350px"] > b',
    whidthAno: ':nth-child(3) > [whidth="350px"] > b',
    whidthOrgao: ':nth-child(4) > [whidth="350px"] > b',
    whidthNumeroSei: ':nth-child(5) > [whidth="350px"] > b',
    whidthProcesso: ':nth-child(6) > [whidth="350px"] > b',
    whidthDataPublicacao: ':nth-child(7) > [whidth="350px"] > b',
    whidthVigenciaDias: ':nth-child(8) > [whidth="350px"] > b',
    whidthDiasRestantes: ':nth-child(9) > [whidth="350px"] > b',
    whidthStatus: ':nth-child(10) > [whidth="350px"] > b',
    whidthAlertaPrazo: ':nth-child(11) > [whidth="350px"] > b',
    whidthTitular: ':nth-child(12) > [whidth="350px"] > b',
    whidthSuplente: ':nth-child(13) > [whidth="350px"] > b',
    whidthArquivadaSuspensaCancelada: ':nth-child(14) > [whidth="350px"] > b',
    whidthDataVencimento: ':nth-child(15) > [whidth="350px"] > b',
    whidthEstudoServicosRelacionados: ':nth-child(16) > [whidth="350px"] > b',
    whidthObservacaoProcessos: ':nth-child(17) > [whidth="350px"] > b',
    whidthDescricao: ':nth-child(18) > [whidth="350px"] > b',
    whidthRa: '.panel-border > .table > tbody > :nth-child(1) > :nth-child(1) > b',
    whidthEmpreendimento: '.panel-border > .table > tbody > :nth-child(2) > :nth-child(1) > b',
    botao1: ':nth-child(4) > .box-header > .box-tools > .btn > .fa',
    botao2: ':nth-child(3) > .box-header > .box-tools > .btn > .fa',
    botao3: ':nth-child(2) > .box-header > .box-tools > .btn > .fa',
    seletorRAForm: '#form_geral > :nth-child(1) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    seletorRAFormGeral: '#form_geral > :nth-child(1) > :nth-child(1) .select2-selection',
    seletorDropdown: '.select2-results li',
    botaoPanel: '.panel > :nth-child(2) > .col-md-4 > .btn',
    valorComp: '#vl_valor_compensacao_ambiental_inicial',
    botaoPanelBody: '.panel-body > :nth-child(2) > .col-md-4 > .btn',
    dataRecebInicio: '#dt_recebimento_ai_inicio',
    limparPesquisa: '[onclick="limpaPesquisa()"]',
    botaoPesquisar: '#pesquisar',
    botaoCadastro: '.btn-success',
    acordeaoCompAmb: 'div.accordion.float-style:contains("Dados Específicos da Compensação Ambiental")',
    acordeaoCompFlo: 'div.accordion.float-style:contains("Dados Específicos da Compensação Florestal")',
    acordeaoComInf: 'div.accordion.float-style:contains("Dados Específicos do Auto de Infração")',
    seletorReg: '#select2-regiao-container',
    seletorEmpreendimento: '#select2-cd_empreendimento-container > .select2-selection__clear',
    adicionarEmpreendimento: 'button:contains("Adicionar")',
    selecionarLicenca: ':nth-child(2) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection',
    numDemanda: '#nr_demanda',
    anoDemanda: '#aa_demanda',
    selecionarOrgao: ':nth-child(3) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection',
    digitarDtPub: '#dt_publicacao',
    digitarQtDias: '#qt_dias_vigencia',
    digitarDesDemanda: '#ds_demanda',
    botaoSalvar: '#submit',
    botaoContinuar: '.modal-footer > .btn-primary',
    modalOk: 'button:contains("OK")',
    irLink: ':nth-child(3) > [href="#"]',
    irLink2: '.menu-open > .treeview-menu > :nth-child(1) > a > span',
    clicarBotaoPesquisar: '#pesquisar',
    clicarPrimeiroBotaoVisualizar: 'a[title="Visualizar"]',
    clicarBotaoVoltar: '[onclick="window.history.back()"]',
    clicarLink3: '.menu-open > .treeview-menu > :nth-child(1) > a > span',
    digitarDtPubInicio: '#dt_publicacao_inicio',
    gerarRelDemandaPDF: '#gerarRelatorioDemandaPDF',
    clicarExcluirDemanda: '#btn-delete-demanda',
    clicarConfirmar: '.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-primary',
    checkPossuiPrazo:'#fl_prazo_cumprimento_cf',
    checkArquivadoCF:'#fl_arquivado_cf',
    dataRecebimentoAI: ':nth-child(5) > :nth-child(1) > .panel-accordion > :nth-child(1) > tbody > :nth-child(1) > :nth-child(2)',
    dataLimiteEnvioRec1Instancia:':nth-child(5) > tbody > :nth-child(5) > :nth-child(2)',
    dataCienciaDecisao1Instancia:':nth-child(5) > tbody > :nth-child(3) > :nth-child(2)',
    dataLimiteEnvioRecurso2Instancia:':nth-child(7) > tbody > :nth-child(5) > :nth-child(2)',
    dataCienciaDecisao2Instancia:':nth-child(7) > tbody > :nth-child(3) > :nth-child(2)',
    dataLimiteEnvioRecurso3Instancia:':nth-child(9) > tbody > :nth-child(5) > :nth-child(2)',
    dataCienciaDecisao3Instancia:':nth-child(9) > tbody > :nth-child(3) > :nth-child(2)',
    dataLimitePagamentoMulta: ':nth-child(9) > tbody > :nth-child(6) > :nth-child(2)',
    dataLimiteCumprimentoCA:':nth-child(3) > :nth-child(1) > .panel-accordion > :nth-child(1) > tbody > :nth-child(5) > :nth-child(2)',
    dataLimiteCumprimentoCF: ':nth-child(4) > :nth-child(1) > .panel-accordion > :nth-child(1) > tbody > :nth-child(9) > :nth-child(2)',
    diasRestantesCF: ':nth-child(3) > :nth-child(1) > .panel-accordion > :nth-child(1) > tbody > :nth-child(6) > :nth-child(2)',
    saldoDevedorCA:'#saldo_CA',
    saldoDevedorCF:'#saldo_CF1',
}
