export const ELEMENTS = {

    campoUsuario: ':nth-child(2) > .form-control',
    campoSenha: ':nth-child(3) > .form-control',
    botaoLogin: '.btn',
    tituloPendencia: 'h1',
    abaEstudo:':nth-child(4) > a > span',
    labelEstudo: 'h1',
    labelRA: '#form_filtro_geral > :nth-child(1) > :nth-child(1) > :nth-child(1) > .form-group > .control-label',
    labelEmpreendimento: '#form_filtro_geral > :nth-child(1) > :nth-child(2) > .form-group > .control-label',
    labelDemanda: '#form_filtro_geral > :nth-child(1) > :nth-child(3) > .form-group > .control-label',
    labelListaPendencia: '#form_filtro_geral > :nth-child(2) > :nth-child(1) > .form-group > label',
    labelTipo: '#form_filtro_geral > :nth-child(2) > :nth-child(2) > .form-group > label',
    labelNatureza: '#form_filtro_geral > :nth-child(2) > :nth-child(3) > .form-group > label',
    labelObjeto: '#form_filtro_geral > :nth-child(2) > :nth-child(4) > .form-group > label',
    labelDescricaoObjeto: '#form_filtro_geral > :nth-child(3) > .col-md-12 > .form-group > .control-label',
    labelStatus: ':nth-child(4) > :nth-child(1) > .form-group > label',
    labelPrevisaoConclusao: ':nth-child(4) > :nth-child(2) > :nth-child(1) > label',
    labelValorEstimado: ':nth-child(5) > :nth-child(1) > :nth-child(1) > label',
    labelDataElaboracao: ':nth-child(5) > :nth-child(2) > :nth-child(1) > label',
    labelTitular: ':nth-child(6) > :nth-child(1) > .form-group > label',
    labelSuplente: ':nth-child(6) > :nth-child(2) > .form-group > label',
    labelDadosContrato: ':nth-child(2) > .box-header > .box-title',
    labelNContrato: '#form_filtro_contrato > :nth-child(1) > :nth-child(1) > .form-group > .control-label',
    labelAnoContrato: '#form_filtro_contrato > :nth-child(1) > :nth-child(2) > .form-group > .control-label',
    labelContratada: '#form_filtro_contrato > :nth-child(1) > :nth-child(3) > .form-group > .control-label',
    labelValorContratoInicial: '#form_filtro_contrato > :nth-child(2) > :nth-child(1) > :nth-child(1) > label',
    labelValorContratoFinal: '#form_filtro_contrato > :nth-child(2) > :nth-child(2) > :nth-child(1) > label',
    labelInicioVigenciaContrato: '#form_filtro_contrato > :nth-child(2) > :nth-child(3) > :nth-child(1) > label',
    labelFimVigenciaContrato: '#form_filtro_contrato > :nth-child(2) > :nth-child(4) > :nth-child(1) > label',
    labelDescricaoObjetoContrato: '#form_filtro_contrato > :nth-child(3) > .col-md-12 > .form-group > .control-label',
    labelDadosOrdem: ':nth-child(3) > .box-header > .box-title',
    labelNumeroOS: ':nth-child(3) > .box-body > .panel > #panel-body > #form_filtro_ordem_servico > .row > :nth-child(1) > .form-group > .control-label',
    labelAnoOS: ':nth-child(3) > .box-body > .panel > #panel-body > #form_filtro_ordem_servico > .row > :nth-child(2) > .form-group > .control-label',
    labelUnidadeResponsavelOS: ':nth-child(3) > .box-body > .panel > #panel-body > #form_filtro_ordem_servico > .row > .col-md-6 > .form-group > .control-label',
    ariaLabelEmpreendimento: '.sorting_asc',
    ariaLabelReferencia: '[aria-label="Referência: Ordenar colunas de forma ascendente"]',
    ariaLabelObjeto: '[aria-label="Objeto: Ordenar colunas de forma ascendente"]',
    ariaLabelStatus: '[aria-label="Status: Ordenar colunas de forma ascendente"]',
    ariaLabelContratoOS: '[aria-label="Contrato | OS: Ordenar colunas de forma ascendente"]',
    ariaLabelAcao: '[aria-label="Ação: Ordenar colunas de forma ascendente"]',
    selectRA: ':nth-child(1) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    selectRAItem: '.select2-results li',
    botaoLimparFormulario: '[onclick="limparFormularioPesquisa()"]',
    botaoNovoCadastro: '.btn-success',
    textoNovoCadastro: '.box-title',
    textoReferencias: "[onclick=\"toggleFormAccordion('rf')\"] > b",
    textoIncluirRequerimento: '#form_estudo_servico > :nth-child(2) > :nth-child(7) > :nth-child(1)',
    labelCadastroRA: ':nth-child(2) > :nth-child(1) > .form-group > .control-label',
    labelCadastroEmpreendimento: '#form_requerimento > :nth-child(3) > .form-group > .control-label',
    labelCadastroTipoRequerimento: '#form_requerimento > :nth-child(4) > .form-group > .control-label',
    labelCadastroRequerimentos: '#form_requerimento > :nth-child(5) > .form-group > label',
    labelCadastroRequerimentosReferenciados: '#form_requerimento > :nth-child(7) > :nth-child(1)',
    labelCadastroRequerimento: '#tabela-estudo-requerimento > thead > tr > .sorting_desc',
    labelCadastroIncluirExigencia: ':nth-child(7) > :nth-child(4)',
    labelFormCadastroRA: '#form_exigencia > :nth-child(1) > :nth-child(1) > .form-group > .control-label',
    labelFormCadastroEmpreendimento: '#form_exigencia > :nth-child(2) > .form-group > .control-label',
    labelFormCadastroDemanda: '#form_exigencia > :nth-child(3) > .form-group > .control-label',
    labelFormCadastroExigencias: '#form_exigencia > :nth-child(4) > .form-group > label',
    labelFormCadastroExigenciasRef: '#form_exigencia > :nth-child(6) > :nth-child(1)',
    tabelaCadastroN: '#tabela-estudo-exigencia > thead > tr > .sorting_desc',
    tabelaCadastroDescricao: '#tabela-estudo-exigencia > thead > tr > .sorting',
    tabelaCadastroAcao: '#tabela-estudo-exigencia > thead > tr > .text-center',
    labelCadastroDadosGerais: "[onclick=\"toggleFormAccordion('gr')\"] > b",
    validarFormCadastroTipo: '#form_dados_gerais > :nth-child(1) > .form-group > label',
    validarFormCadastroNatureza: '#form_dados_gerais > :nth-child(2) > .form-group > .control-label',
    validarLabelCadastroObjeto: ':nth-child(3) > .control-label',
    validarFormCadastroDescricao: '#form_dados_gerais > :nth-child(4) > .form-group > .control-label',
    validarFormCadastroAreaPoligonal: '#form_dados_gerais > :nth-child(5) > .form-group > .control-label',
    validarFormCadastroStatus: '#form_dados_gerais > :nth-child(6) > .form-group > .control-label',
    validarFormCadastroDescricaoStatus: '#form_dados_gerais > :nth-child(7) > .form-group > .control-label',
    validarFormCadastroOrgaoExterno: '#form_dados_gerais > :nth-child(8) > .form-group > .control-label',
    validarFormCadastroValorEstimado: '#form_dados_gerais > :nth-child(9) > .form-group > .control-label',
    validarFormCadastroProcessoSEI: '#form_dados_gerais > :nth-child(10) > .form-group > label',
    validarFormCadastroTitular: ':nth-child(11) > .form-group > .control-label',
    validarFormCadastroSuplente: ':nth-child(12) > .form-group > .control-label',
    validarFormCadastroCaminhoDepart: ':nth-child(13) > .form-group > .control-label',
    validarFormCadastroDataElaboracao: ':nth-child(14) > .control-label',
    validarFormCadastroPrevisaoConclusaoEstudo: ':nth-child(15) > .control-label',
    validarFormCadastroDadosContrato: "[onclick=\"toggleFormAccordion('ct')\"] > b",
    validarFormCadastro: '#ct_plus',
    validarFormCadastroNumeroContrato: '#form_contrato_gec > :nth-child(2) > .form-group > .control-label',
    validarFormCadastroAnoContrato: '#form_contrato_gec > :nth-child(3) > .form-group > .control-label',
    validarFormCadastroContratada: '#form_contrato_gec > :nth-child(5) > .form-group > .control-label',
    validarFormCadastroValorContratoInicial: '#form_contrato_gec > :nth-child(6) > .form-group > .control-label',
    validarFormCadastroValorContrato: '#form_contrato_gec > :nth-child(7) > .form-group > .control-label',
    validarFormCadastroInicioVigenciaContrato: '#form_contrato_gec > :nth-child(8) > .form-group > .control-label',
    validarFormCadastroFimVigenciaContrato: '#form_contrato_gec > :nth-child(9) > .form-group > .control-label',
    validarFormCadastroDescricaObjetoContrato: ':nth-child(10) > .form-group > .control-label',
    validarFormCadastroDadosOrdemServico: "[onclick=\"toggleFormAccordion('os')\"] > b",
    clicarBotaoMais: '#os_plus',
    selecionarRegiaoAdmin: '#select2-cd_regiao_admin_req-container',
    seletorDropdown: '.select2-results li',
    selecionarEmpreendimento: '#select2-cd_empreendimento_req-container > .select2-selection__clear',
    selecionarTpRequerimento: '#select2-tp_requerimento-container',
    selecionarCdRequerimento: '#select2-cd_requerimento-container > .select2-selection__clear',
    clicarBotaoAdicionarRequerimento: '#btnAdicionar_requerimento',
    selecionarRegiaoAdminExi: '#select2-cd_regiao_admin_exi-container',
    selecionarEmpreendimentoExi: '#select2-cd_empreendimento_exi-container > .select2-selection__clear',
    selecionarDemandaContainer: '#select2-cd_demanda-container > .select2-selection__clear',
    selecionarExigenciaContainer: '#select2-cd_exigencia-container > .select2-selection__clear',
    clicarBotaoAdicionarExigencia: '#btnAdicionar_exigencia',
    selecionarTpEstudoContainer: '#select2-tp_estudo-container',
    selecionarTpNaturezaContainer: '#select2-tp_natureza-container',
    selecionarTpObjetoContainer: '#select2-tp_objeto-container',
    selecionarTpStatusContainer: '#select2-tp_status-container',
    selecionarCdPessoaTitularContainer: '#select2-cd_pessoa_titular-container',
    selecionarCdPessoaSuplenteContainer: '#select2-cd_pessoa_suplente-container',
    clicarBotaoSalvar: '#btnSalvar',
    clicarBotaoContinuar: '.modal-footer > .btn-primary',
    clicarBotaoOk: '.modal-footer > .btn-danger',
    clicarBotaoVoltar: '[onclick="window.history.back()"]',
    selecionarPesTitular: ':nth-child(6) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    selecionarPesSuplente: ':nth-child(6) > :nth-child(2) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    botaoPesquisar: '#pesquisar',
    clicarPrimeiroBotaoEditar: 'a[title="Editar"]',
    validarTituloEditar: '.box-title',
    seletorPessoaTitular: '#select2-cd_pessoa_titular-container > .select2-selection__clear',
    seletorPessoaSuplente: '#select2-cd_pessoa_suplente-container > .select2-selection__clear',
    clicarPrimeiroBotaoExcluir: 'a[title="Excluir"]',
    clicarModalOk: '.modal-footer > .btn',
    validarAriaLabelContratoOS: '[aria-label="Contrato | OS: Ordenar colunas de forma ascendente"]',
    validarAriaLabelAcao: '[aria-label="Ação: Ordenar colunas de forma ascendente"]',
    selecionarRA: ':nth-child(1) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    limparFormularioPesquisa: '[onclick="limparFormularioPesquisa()"]',
    botaoNovoCadastro2: '.btn-success',
    validarTextoNovoCadastro: '.box-title',
    validarTextoReferencias: "[onclick=\"toggleFormAccordion('rf')\"] > b",
    validarTextoIncluirRequerimento: '#form_estudo_servico > :nth-child(2) > :nth-child(7) > :nth-child(1)',
    validarLabelCadastroRA: ':nth-child(2) > :nth-child(1) > .form-group > .control-label',
    validarLabelCadastroEmpreendimento: '#form_requerimento > :nth-child(3) > .form-group > .control-label',
    validarLabelCadastroTipoRequerimento: '#form_requerimento > :nth-child(4) > .form-group > .control-label',
    validarLabelCadastroRequerimentos: '#form_requerimento > :nth-child(5) > .form-group > label',
    validarLabelCadastroRequerimentosReferenciados: '#form_requerimento > :nth-child(7) > :nth-child(1)',
    validarLabelCadastroRequerimento: '#tabela-estudo-requerimento > thead > tr > .sorting_desc',
    validarLabelCadastroIncluirExigencia: ':nth-child(7) > :nth-child(4)',
    validarFormCadastroRA: '#form_exigencia > :nth-child(1) > :nth-child(1) > .form-group > .control-label',
    validarFormCadastroEmpreendimento: '#form_exigencia > :nth-child(2) > .form-group > .control-label',
    validarFormCadastroDemanda: '#form_exigencia > :nth-child(3) > .form-group > .control-label',
    validarFormCadastroExigencias: '#form_exigencia > :nth-child(4) > .form-group > label',
    validarFormCadastroExigenciasRef: '#form_exigencia > :nth-child(6) > :nth-child(1)',
    validarTabelaCadastroN: '#tabela-estudo-exigencia > thead > tr > .sorting_desc',
    validarTabelaCadastroDescricao: '#tabela-estudo-exigencia > thead > tr > .sorting',
    validarTabelaCadastroAcao: '#tabela-estudo-exigencia > thead > tr > .text-center',
    validarLabelCadastroDadosGerais: "[onclick=\"toggleFormAccordion('gr')\"] > b"
}
