export const ELEMENTS = {

    campoUsuario: ':nth-child(2) > .form-control',
    campoSenha: ':nth-child(3) > .form-control',
    botaoLogin: '.btn',
    dropdownGla:'.select2-results',
    abaLateralEmpreendimento:':nth-child(1) > .form-group > .text-block > a',
    abaDemanda:':nth-child(2) > .form-group > .text-block > a',
    coExigencia:'#co_exigencia',
    botaoLimparExigencia:'[onclick="limpaExigencia()"]',
    seletorTema:':nth-child(4) > :nth-child(2) > .form-group > .select2-container > .selection > .select2-selection',
    campoPrazoDias:'#qt_prazo_dias',
    seletorPessoaTitular:'#select2-cd_pessoa_titular-container',
    seletorSuplente:'#select2-cd_pessoa_suplente-container',
    seletorStatus:':nth-child(9) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection',
    orgaoProcessoSei:'#cd_orgao_processo_sei',
    numeroProcessoSei:'#nr_processo_sei',
    anoProcessoSei: '#aa_processo_sei',
    seletorUnidadeInterna:':nth-child(10) > :nth-child(1) > .panel-border > .panel-body > .row > .col-md-10 > .form-group > .select2-container > .selection > .select2-selection',
    adicionarUnidadeInterna: '#add_unidade_interna',
    botaoSalvar:'#submit',
    botaoDemanda:':nth-child(3) > [href="#"] > :nth-child(2)',
    botaoConsultaDemanda:'.menu-open > .treeview-menu > :nth-child(1) > a > span',
    seletorRA:'#form_geral > :nth-child(1) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    seletorEmpreendimento:'#form_geral > :nth-child(1) > :nth-child(2) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    botaoPesquisar:'#pesquisar',
    filtroPesquisarDemanda:'#table-demanda_filter > label > .form-control',
    primeiroBotaoVisualizar: 'a[title="Visualizar"]',
    abaExigencia: '.exigencias-aba',
    botaoNovaExigencia:'#exigencia > .box > .box-body > .panel > .panel-body > .panel-footer > .btn-toolbar > a.btn-success',
    abaLateralExigencia:':nth-child(6) > a > span',
    modalAvisoFiltros:'.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn',
    seletorRegiao:'#select2-cd_regiao-container',
    seletorEmpreendimentoPesquisarExigencias:'#select2-cd_empreendimento-container',
    botaoPesquisarExigencia: '#pesquisarExigencia',
    campoFiltroPesquisa: '#table-exigencia_filter > label > .form-control',
    descricaoObservacaoSeiPedido:'#ds_observacao_sei_pedido',
    botaoConfirmar:'.modal-footer > .btn-primary',
    botaoEditarDilacaoPrazos:'[title="Editar"] > .fa',
    botaoExcluir:'[title="Excluir"] > .fas',
    botaoLinkEditarExigencia: '#exigencia-aba > .panel-footer > :nth-child(1) > a.btn',
    botaoModalSalvar: '.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-primary',
    labelCoExigencia: '#co_exigencia',
    botaoDeleteExigencia:'.btn-delete-exigencia > .fas',
    modalRelatorioPDF:'#modalRelatorioPersonalizadoPDF',
    gerarRelatorioPDF: '#gerarRelatorioPersonalizadoPDF',
    botaoFecharModalPDF: '#modal-relatorio-pdf-personalizado > .modal-dialog > .modal-content > .modal-footer > .btn-form',
    labelEmpreendimento:':nth-child(3) > :nth-child(1) > .form-group > label',
    labelDemanda: ':nth-child(3) > :nth-child(2) > .form-group > label',
    labelNumero: ':nth-child(4) > :nth-child(1) > .form-group > .control-label',
    labelTema: ':nth-child(2) > .form-group > .control-label',
    labelPossuiPrazoExpresso: '.col-md-10 > .form-check-label',
    labelDias: '.col-md-2 > .form-check-label',
    labelPrevisaoCumprimento: ':nth-child(5) > :nth-child(1) > .form-group > .control-label',
    labelExigeContratacao: '.form-group > .form-check-label',
    labelDescricaoExigencia: ':nth-child(6) > .col-md-12 > .form-group > .control-label',
    labelDescricaoProvidencia: ':nth-child(7) > .col-md-12 > .form-group > .control-label',
    labelTitular: ':nth-child(8) > :nth-child(1) > .form-group > label',
    labelSuplente: ':nth-child(8) > :nth-child(2) > .form-group > label',
    labelStatus: ':nth-child(9) > :nth-child(1) > .form-group > .control-label',
    labelSeiProcAcompanhamento: ':nth-child(2) > :nth-child(1) > .form-group > label',
    labelUnidadeInterna: ':nth-child(10) > :nth-child(1) > .panel-border > .panel-body > .row > .col-md-10 > .form-group > .control-label',
    tabelaUnidadeInterna: ':nth-child(10) > :nth-child(1) > .panel-border > .panel-body > .row > .col-md-12 > :nth-child(1) > tbody > tr > th',
    labelUnidadeExterna: ':nth-child(11) > :nth-child(1) > .panel-border > .panel-body > .row > .col-md-10 > .form-group > .control-label',
    tabelaUnidadeExterna: ':nth-child(11) > :nth-child(1) > .panel-border > .panel-body > .row > .col-md-12 > :nth-child(1) > tbody > tr > th',

    //validar campos de texto de Dilações de Prazos
    labelSeiRequerimento: ':nth-child(2) > .col-md-8 > .form-group > .control-label',
    labelSeiDeferimentoIndeferimento: ':nth-child(3) > .col-md-8 > .form-group > .control-label',
    labelStatusModal: ':nth-child(2) > .col-md-4 > .form-group > .control-label',
    labelDataLimiteDilacaoPrazo: '.modal-body > :nth-child(3) > .col-md-4 > .form-group > .control-label',

    //validando campos de texto de relatório de acompanhamento de exigências
    labelRaEmpreendimentoDemanda: '#modal-relatorio-pdf-personalizado > .modal-dialog > .modal-content > .modal-body > :nth-child(3) > :nth-child(1) > .form-group > .form-check-label',
    labelNumeroModal: ':nth-child(4) > :nth-child(1) > .form-group > .form-check-label',
    labelUnidadesResponsaveis: ':nth-child(4) > :nth-child(4) > .form-group > .form-check-label',
    labelDataLimiteModal: ':nth-child(4) > :nth-child(7) > .form-group > .form-check-label',
    labelInformativa: ':nth-child(6) > :nth-child(4) > .form-group > .form-check-label',
    labelDispensada: ':nth-child(6) > :nth-child(7) > .form-group > .form-check-label',
    labelSeiDilacaoAnalise: '#modal-relatorio-pdf-personalizado > .modal-dialog > .modal-content > .modal-body > :nth-child(3) > :nth-child(2) > .form-group > .form-check-label',
    labelDescricaoProvidenciaModal: ':nth-child(4) > :nth-child(2) > .form-group > .form-check-label',
    labelDescricaoExigenciaModal: ':nth-child(4) > :nth-child(5) > .form-group > .form-check-label',
    labelCumprida: ':nth-child(6) > :nth-child(5) > .form-group > .form-check-label',
    labelEmExecucao: ':nth-child(6) > :nth-child(8) > .form-group > .form-check-label',
    labelTemaModal: ':nth-child(4) > :nth-child(3) > .form-group > .form-check-label',
    labelEstudosServRelacionados: ':nth-child(4) > :nth-child(6) > .form-group > .form-check-label',
    labelPendente: ':nth-child(6) > :nth-child(6) > .form-group > .form-check-label',
}


