export const ELEMENTS = {

    campoUsuario: ':nth-child(2) > .form-control',
    campoSenha: ':nth-child(3) > .form-control',
    botaoLogin: '.btn',
    textoPendencia: 'h1',
    abaDemandas:':nth-child(3) > [href="#"]',
    menuDemandasAssociacao: '.menu-open > .treeview-menu > :nth-child(2) > a > span',
    tituloAssocDemanda: 'h1',
    tituloAssocPesquisar: '.box-title',
    labelAssocTipoAssoc: '.col-md-4 > .form-group > .control-label',
    labelAssocRA: ':nth-child(2) > :nth-child(1) > .form-group > .control-label',
    labelAssocEmpreendimento: ':nth-child(2) > .form-group > .control-label',
    selectTpAssociacao: '#select2-tp_associacao-container',
    opcaoSelect2: '.select2-results__option',
    botaoModalSalvar: '.modal-footer > .btn-primary',
    listaSelect2: '.select2-results',
    selectRegiaoAdmin: '#select2-cd_regiao_admin-container',
    limparEmpreendimento: '#select2-cd_empreendimento-container > .select2-selection__clear',
    botaoLimparForm: '[onclick="limparFormularioPesquisa()"]',
    botaoNovoCadastro: '.btn-success',
    labelNovoTipoAssoc: ':nth-child(1) > :nth-child(1) > .form-group > label',
    labelNovoRA: ':nth-child(1) > .form-group > .control-label',
    labelNovoEmpreendimento: ':nth-child(3) > .form-group > .control-label',
    labelNovoDemandas: ':nth-child(4) > .form-group > label',
    tabelaRA: 'tr > :nth-child(1)',
    tabelaEmpreendimento: 'tr > :nth-child(2)',
    tabelaDemandas: 'tr > :nth-child(3)',
    tabelaArquivada: 'tr > :nth-child(4)',
    tabelaAcao: '.text-center',
    selectTpAssociacaocont: '#select2-tp_associacao-container',
    selectDemanda: '#select2-cd_demanda-container',
    botaoAdicionar: '#btnAdicionar',
    botaoExcluir: '.text-center > .fas',
    selectCdEmpreendimento: '#select2-cd_empreendimento-container',
    botaoSalvar: '#btnSalvar',
    botaoModalOk: '.modal-footer > .btn',
    botaoModalBTNOk: '.modal-footer > .btn-primary',
    botaoVoltar: '[onclick="window.history.back()"]',
    botaoPesquisar: '#pesquisar',
    primeiroBotaoEditar: 'a[title="Editar"]',
    primeiroBotaoVisualizar: 'a[title="Visualizar"]',
    primeiroBotaoExcluir: 'a[title="Excluir"]',
    botaoExcluirAssocDemand: '#btn-delete-associacao-demanda'
}
