/// <reference types="cypress" />

import demandas_consultar from "../../../support/pages/demandas_consultar";

describe('pendência', () => {
    beforeEach(() => {
        cy.viewport(1980, 1200)
       
          
    })
    it('teste demandas-consultar', () => {
        //abrindo a aba de consultar demandas
        demandas_consultar.irParaGLA()
        demandas_consultar.login()
        demandas_consultar.validarTextoPendencia()
        demandas_consultar.irAbaDemanda()
        demandas_consultar.irAbaDemandaConsultar()

        //validando os campos da aba de demandas
        demandas_consultar.validarTituloDemanda()
        demandas_consultar.validarTituloDados()
        demandas_consultar.validarFormRA()
        demandas_consultar.validarFormEmpreendimento()
        demandas_consultar.validarFormPossuiExigencia()
        demandas_consultar.validarFormTipo()
        demandas_consultar.validarFormNumero()
        demandas_consultar.validarFormAno()
        demandas_consultar.validarLabelPossuiReq()
        demandas_consultar.validarLabelOrgaoDemanda()
        demandas_consultar.validarLabelDescricao()
        demandas_consultar.validarLabelPeriodoData()
        demandas_consultar.validarLabelPeriodoVig()
        demandas_consultar.validarLabelStatus()
        demandas_consultar.validarLabelAlerta()
        demandas_consultar.validarLabelPeriodoDias()
        demandas_consultar.validarLabelTitular()
        demandas_consultar.validarLabelSuplente()
        demandas_consultar.validarLabelEmpreenResp()
        demandas_consultar.validarLabelPeriodoRestante()
        demandas_consultar.clicarBotao1()
        demandas_consultar.clicarBotao2()
        demandas_consultar.clicarBotao3()
        demandas_consultar.validarFormAmbValTotal()
        demandas_consultar.validarFormAmbVR()
        demandas_consultar.validarFormAmbGrauImpacto()
        demandas_consultar.validarFormAmbPrazoLimite()
        demandas_consultar.validarFormAmbArquivada()
        demandas_consultar.validarFormAmbDescricao()
        demandas_consultar.validarFormAmbStatusRecurso()
        demandas_consultar.validarFormAmbDataLimite()
        demandas_consultar.validarFormAmbDiasRestantes()
        demandas_consultar.validarFormAmbSaldoDevedor()
        demandas_consultar.validarFormFlorestLegRef()
        demandas_consultar.validarFormFlorestTipoVeg()
        demandas_consultar.validarFormFlorestModalPag()
        demandas_consultar.validarFormFlorestQtdMudasEst()
        demandas_consultar.validarFormFlorestQtdMudasDef()
        demandas_consultar.validarFormFlorestValorTotal()
        demandas_consultar.validarFormFlorestAreaTotal()
        demandas_consultar.validarFormFlorestDataLimite()
        demandas_consultar.validarFormFlorestDiasRestantes()
        demandas_consultar.validarFormFlorestArquivada()
        demandas_consultar.validarFormFlorestDescricao()
        demandas_consultar.validarFormFlorestStatusRecurso()
        demandas_consultar.validarFormFlorestSaldoDevedor()
        demandas_consultar.validarFormAIDataReceb()
        demandas_consultar.validarFormAITipoSancao()
        demandas_consultar.validarFormAIValorMulta()
        demandas_consultar.validarFormAITipoAtividade()
        demandas_consultar.validarFormAIOrgaoDescricao()
        demandas_consultar.validarFormAIStatus()
        demandas_consultar.validarFormAIInstancia()
        demandas_consultar.validarFormAIDescricaoStatus()
        demandas_consultar.validarFormAITituloPrazos()
        demandas_consultar.validarFormAIPeriodosInstancia()
        demandas_consultar.validarFormAIDataEnvio()
        demandas_consultar.validarFormAIDataCiencia()
        demandas_consultar.validarFormAIValorAtual()
        demandas_consultar.validarFormAIDataLimiteEnvio()
        demandas_consultar.validarFormAIDataLimitePagamento()
        demandas_consultar.validarLabelDadosCA()
        demandas_consultar.validarLabelDadosCF()
        demandas_consultar.validarLabelDadosAI()
        demandas_consultar.validarLabelValorCA()
        demandas_consultar.validarLabelLegRef()
        demandas_consultar.validarLabelDataRecebAI()
        demandas_consultar.validarLabelDiasRestCA()
        demandas_consultar.validarLabelValorCF()
        demandas_consultar.validarLabelTipoSancao()
        demandas_consultar.validarLabelSubtotalCA()
        demandas_consultar.validarLabelDiasRestCF()
        demandas_consultar.validarLabelTipoVegetacao()
        demandas_consultar.validarLabelModPagamento()
        demandas_consultar.validarLabelSubtotalMultaAI()
        demandas_consultar.validarTabelaRA()
        demandas_consultar.validarTabelaEmpreendimento()
        demandas_consultar.validarTabelaTipo()
        demandas_consultar.validarTabelaNumero()
        demandas_consultar.validarTabelaAno()
        demandas_consultar.validarTabelaOrgao()
        demandas_consultar.validarTabelaDiasRest()
        demandas_consultar.validarTabelaAlerta()
        demandas_consultar.validarTabelaTitular()
        demandas_consultar.validarTabelaAcao()

        //teste de adicionar e apagar os campos
        demandas_consultar.seletorRAFormGeral()
        demandas_consultar.seletorDropdown('RA-I - BRASILIA ')
        cy.wait(4000)
        demandas_consultar.clicarBotao()
        demandas_consultar.digitarValorComp('1000')
        cy.wait(4000)
        demandas_consultar.clicarBotaoPanel()
        demandas_consultar.digitarDataRecebInicio('2022-01-01')
        cy.wait(3000)
        demandas_consultar.limparPesquisa()

        //testando o campo de pesquisa
        demandas_consultar.selecionarRA()
        demandas_consultar.seletorDropdown('RA-I - BRASILIA ')
        demandas_consultar.clicarBotaoPesquisar()

        //testando o cadastro de uma nova demanda
        demandas_consultar.clicarBotaoCadastro()
        demandas_consultar.validarTituloNovaDemanda()
        demandas_consultar.validarAccordionDadosGerais()
        demandas_consultar.validarAccordionDadosCA()
        demandas_consultar.validarAccordionDadosCF()
        demandas_consultar.validarAccordionDadosAI()
        demandas_consultar.clicarAcordeaoCompAmb()
        demandas_consultar.clicarAcordeaoCompFlo()
        demandas_consultar.clicarAcordeaoComInf()
        demandas_consultar.validarFormRA_Especifico()
        demandas_consultar.validarFormEmpreendimento_Especifico()
        demandas_consultar.validarFormTipo_Especifico()
        demandas_consultar.validarFormNumero_Especifico()
        demandas_consultar.validarFormAno_Especifico()
        demandas_consultar.validarFormOrgaoDemanda_Especifico()
        demandas_consultar.validarFormProcessoSEI_Especifico()
        demandas_consultar.validarFormDataPublicacao_Especifico()
        demandas_consultar.validarFormVigenciaDias_Especifico()
        demandas_consultar.validarFormTitular_Especifico()
        demandas_consultar.validarFormSuplente_Especifico()
        demandas_consultar.validarFormDescricao_Especifico()
        demandas_consultar.selecionarReg()
        demandas_consultar.seletorDropdown('RA-I - BRASILIA ')
        demandas_consultar.seletorEmpreendimento()
        cy.wait(2000)
        demandas_consultar.seletorDropdown('103 - Estagio de produção ')
        demandas_consultar.adicionarEmpreendimento()
        demandas_consultar.selecionarLicenca()
        demandas_consultar.seletorDropdown('LP - Licença Prévia')
        demandas_consultar.digitarNumDemanda('10000')
        demandas_consultar.digitarAnoDemanda(2026)
        demandas_consultar.selecionarOrgao()
        demandas_consultar.seletorDropdown('ABDI - AGENCIA BRASILEIRA DE DESENVOLVIMENTO INDUSTRIAL ')
        demandas_consultar.digitarData('2025-07-10')
        demandas_consultar.digitar1('6')
        demandas_consultar.digitar2('teste123')
        demandas_consultar.digitar('111111')
        demandas_consultar.digitarNRProcesso('11111111')
        demandas_consultar.digitarAnoProcesso('2025')
        demandas_consultar.botaoSalvar()
        demandas_consultar.botaoContinuar()
        demandas_consultar.botaoOk()
        demandas_consultar.validarVisualizarTituloDemanda()
        demandas_consultar.validarVisualizarInfoEmpreendimentos()
        demandas_consultar.validarVisualizarDadosGerais()
        demandas_consultar.validarVisualizarInfoDocumento()
        demandas_consultar.validarVisualizarCompensacaoAmbiental()
        demandas_consultar.validarVisualizarCompensacaoFlorestal()
        demandas_consultar.validarVisualizarAutoInfracao()
        demandas_consultar.clicarAdicionar1()
        demandas_consultar.clicarAdicionar2()
        demandas_consultar.clicarAdicionar3()
        demandas_consultar.clicarAdicionar4()
        demandas_consultar.clicarAdicionar5()
        demandas_consultar.validarWhidthTipo()
        demandas_consultar.validarWhidthNumero()
        demandas_consultar.validarWhidthAno()
        demandas_consultar.validarWhidthOrgao()
        demandas_consultar.validarWhidthNumeroSei()
        demandas_consultar.validarWhidthProcesso()
        demandas_consultar.validarWhidthDataPublicacao()
        demandas_consultar.validarWhidthVigenciaDias()
        demandas_consultar.validarWhidthDiasRestantes()
        demandas_consultar.validarWhidthStatus()
        demandas_consultar.validarWhidthAlertaPrazo()
        demandas_consultar.validarWhidthTitular()
        demandas_consultar.validarWhidthSuplente()
        demandas_consultar.validarWhidthArquivadaSuspensaCancelada()
        demandas_consultar.validarWhidthDataVencimento()
        demandas_consultar.validarWhidthEstudoServicosRelacionados()
        demandas_consultar.validarWhidthObservacaoProcessos()
        demandas_consultar.validarWhidthDescricao()
        demandas_consultar.validarWhidthRa()
        demandas_consultar.validarWhidthEmpreendimento()
        demandas_consultar.clicarAbaDoc()
        cy.wait(3000)
        demandas_consultar.clicarExigAba()
        cy.wait(3000)
        demandas_consultar.clicarReqAba()
        cy.wait(3000)
        demandas_consultar.clicarNovoEstudoAba()
        cy.wait(3000)
        demandas_consultar.clicarDemandaAba()
        demandas_consultar.clicarBotaoEditar()
        cy.wait(4000)
        demandas_consultar.digitarDtPub('2025-01-01')
        demandas_consultar.digitarQtDias('9')
        demandas_consultar.digitarDesDemanda('teste2.0')
        demandas_consultar.botaoSalvar()
        demandas_consultar.botaoContinuar()
        demandas_consultar.modalOk()

        // validação da pesquisa
        demandas_consultar.irLink()
        demandas_consultar.irLink2()
        cy.wait(2000)
        demandas_consultar.clicarBotaoPesquisar()
        demandas_consultar.clicarPrimeiroBotaoVisualizar()
        demandas_consultar.clicarBotaoVoltar()
        demandas_consultar.irLink()
        demandas_consultar.clicarLink3()
        demandas_consultar.digitarDtPubInicio('2025-01-01')
        demandas_consultar.clicarBotaoPesquisar()
        demandas_consultar.gerarRelDemandaPDF()

        // validação do botão excluir
        demandas_consultar.clicarPrimeiroBotaoVisualizar()
        cy.wait(10000)
        demandas_consultar.clicarExcluirDemanda()
        demandas_consultar.clicarConfirmar()
    })
})
