/// <reference types="cypress" />

import demandas_associacao from "../../../support/pages/demandas_associacao";

describe('pendência', () => {
    beforeEach(() => {
        //cy.visit('http://gla-homol.terracapnet.local')
        cy.viewport(1980, 1200)


    })
    it('teste Associação-consultar', () => {
        demandas_associacao.irParaGLA()
        demandas_associacao.login()
        //abrindo a aba de consultar Associação
        // cy.get(':nth-child(2) > .form-control').type('C9020840')
        // cy.get(':nth-child(3) > .form-control').type('welcome_1')
        // cy.get('.btn').click()
        demandas_associacao.validarTextoPendencia()
        //cy.get('h1').should('have.text', "Pendência")
        demandas_associacao.irParaDemandas()
        //cy.get(':nth-child(3) > [href="#"]').click()
        demandas_associacao.irParaDemandasAssociacao()
        //cy.get('.menu-open > .treeview-menu > :nth-child(2) > a > span').click()

        //validando os campos da aba da associação
        demandas_associacao.validarAbaAssocDemanda()
        //cy.get('h1').should('have.text', "Associação de Demanda")
        demandas_associacao.validarAbaAssocPesquisar()
        //cy.get('.box-title').should('have.text', "Pesquisar")
        demandas_associacao.validarAbaAssocTipoAssoc()
        //cy.get('.col-md-4 > .form-group > .control-label').should('have.text', "Tipo de Associação")
        demandas_associacao.validarAbaAssocRA()
        //cy.get(':nth-child(2) > :nth-child(1) > .form-group > .control-label').should('have.text', "R.A")
        demandas_associacao.validarAbaAssocEmpreendimento()
        //cy.get(':nth-child(2) > .form-group > .control-label').should('have.text', "Empreendimento")

        //teste do botão limpar da aba da associação
        demandas_associacao.seletorTipo()
        //cy.get('.col-md-4 > .form-group > .select2-container > .selection > .select2-selection').click()
        demandas_associacao.seletorDropdown('Geral')
        //cy.get('.select2-results').find('li').contains('Geral').click({force: true})
        demandas_associacao.seletorRegiaoAdmin()
        //cy.get('#select2-cd_regiao_admin-container').click()
        demandas_associacao.seletorDropdown('RA-I - BRASILIA')
        //cy.get('.select2-results').find('li').contains('RA-I - BRASILIA').click({force: true})
        demandas_associacao.seletorEmpreendimento()
        //cy.get('#select2-cd_empreendimento-container > .select2-selection__clear').click()
        demandas_associacao.seletorDropdown('103 - Estagio de produção')
        //cy.get('.select2-results').find('li').contains('103 - Estagio de produção').click({force: true})
        demandas_associacao.limparFormularioPesquisa()
        //cy.get('[onclick="limparFormularioPesquisa()"]').click()

        //validação de novo cadastro
        demandas_associacao.clicarBotaoNovoCadastro()
        //cy.get('.btn-success').click()
        demandas_associacao.validarNovoCadasLabelNovoCadas()
        //cy.get('.box-title').should('have.text', "Novo Cadastro")
        demandas_associacao.validarNovoCadasLabelTipoAssoc()
        //cy.get(':nth-child(1) > :nth-child(1) > .form-group > label').should('have.text', "Tipo de Associação *")
        demandas_associacao.validarNovoCadasLabelRA()
        //cy.get(':nth-child(1) > .form-group > .control-label').should('have.text', "R.A")
        demandas_associacao.validarNovoCadasLabelEmpreendimento()
        //cy.get(':nth-child(3) > .form-group > .control-label').should('have.text', "Empreendimento")
        demandas_associacao.validarNovoCadasLabelDemandas()
        //cy.get(':nth-child(4) > .form-group > label').should('have.text', "Demandas *")

        demandas_associacao.validarNovoCadasTabelaRA()
        //cy.get('tr > :nth-child(1)').should('have.text', "R.A")
        demandas_associacao.validarNovoCadasTabelaEmpreendimento()
        //cy.get('tr > :nth-child(2)').should('have.text', "Empreendimento")
        demandas_associacao.validarNovoCadasTabelaDemandas()
        //cy.get('tr > :nth-child(3)').should('have.text', "Demandas")
        demandas_associacao.validarNovoCadasTabelaArquivada()
        //cy.get('tr > :nth-child(4)').should('have.text', "Arquivada")
        demandas_associacao.validarNovoCadasTabelaAcao()
        //cy.get('.text-center').should('have.text', "Ação")

        //validação de novo cadastro
        demandas_associacao.selecionarTpAssociacao()
        //cy.get('#select2-tp_associacao-container').click()
        demandas_associacao.seletorDropdown('Geral')
        //cy.get('.select2-results').find('li').contains('Geral').click({force: true})
        demandas_associacao.seletorRegiaoAdmin()
        //cy.get('#select2-cd_regiao_admin-container').click()
        demandas_associacao.seletorDropdown('RA-I - BRASILIA')
        //cy.get('.select2-results').find('li').contains('RA-I - BRASILIA').click({force: true})
        demandas_associacao.seletorEmpreendimento()
        //cy.get('#select2-cd_empreendimento-container > .select2-selection__clear').click()
        demandas_associacao.seletorDropdown('103 - Estagio de produção')
        //cy.get('.select2-results').find('li').contains('103 - Estagio de produção').click({force: true})
        demandas_associacao.seletorDemanda()
        //cy.get('#select2-cd_demanda-container').click()
        demandas_associacao.seletorDropdown('LOC - Licença de Operação Corretiva nº 07/04/2025')
        // cy.get('.select2-results').find('li').contains('LOC - Licença de Operação Corretiva nº 07/04/2025').click({force: true})
        demandas_associacao.clicarBotaoAdicionar()
        //cy.get('#btnAdicionar').click()
        demandas_associacao.clicarExcluir()
        //validação da exclução de novo cadastro
        //cy.get('.text-center > .fas').click()


        //validação do botão voltar
        demandas_associacao.clicarBotaoVoltar()
        //cy.get('[onclick="window.history.back()"]').click()
        //salvamento de novo cadastro
        demandas_associacao.clicarBotaoNovoCadastro()
        //cy.get('.btn-success').click()
        demandas_associacao.seletorTpAssociacao()
        //cy.get('#select2-tp_associacao-container').click()
        demandas_associacao.seletorDropdown('Geral')
        //cy.get('.select2-results').find('li').contains('Geral').click({force: true})
        demandas_associacao.seletorRegiaoAdmin()
        //cy.get('#select2-cd_regiao_admin-container').click()
        demandas_associacao.seletorDropdown('RA-I - BRASILIA')
        //cy.get('.select2-results').find('li').contains('RA-I - BRASILIA').click({force: true})
        demandas_associacao.seletorCdEmpreendimento()
        //cy.get('#select2-cd_empreendimento-container').click()
        demandas_associacao.seletorDropdown('103 - Estagio de produção')
        //cy.get('.select2-results').find('li').contains('103 - Estagio de produção').click({force: true})
        demandas_associacao.seletorDemanda()
        //cy.get('#select2-cd_demanda-container').click()
        demandas_associacao.seletorDropdown('LOC - Licença de Operação Corretiva nº 07/04/2025')
        //cy.get('.select2-results').find('li').contains('LOC - Licença de Operação Corretiva nº 07/04/2025').click({force: true})
        demandas_associacao.clicarBotaoAdicionar()
        //cy.get('#btnAdicionar').click()
        demandas_associacao.botaoSalvar()
        //cy.get('#btnSalvar').click()
        demandas_associacao.clicarModalOk()
        //cy.get('.modal-footer > .btn').should('be.visible').and('contain.text', 'OK').click();
        demandas_associacao.seletorRegiaoAdmin()
        //cy.get('#select2-cd_regiao_admin-container').click()
        demandas_associacao.seletorDropdown('RA-II - GAMA')
        //cy.get('.select2-results').find('li').contains('RA-II - GAMA').click({force: true})
        demandas_associacao.seletorEmpreendimento()
        //cy.get('#select2-cd_empreendimento-container > .select2-selection__clear').click()
        demandas_associacao.seletorDropdown('8 - FAZENDA VINICIUS')
        //cy.get('.select2-results').find('li').contains('8 - FAZENDA VINICIUS').click({force: true})
        demandas_associacao.seletorDemanda()
        //cy.get('#select2-cd_demanda-container').click()
        demandas_associacao.seletorDropdown('MP - Manifestação de Pendências nº 1/2024')
        //cy.get('.select2-results').find('li').contains('MP - Manifestação de Pendências nº 1/2024').click({force: true})
        demandas_associacao.clicarBotaoAdicionar()
        //cy.get('#btnAdicionar').click()
        demandas_associacao.botaoSalvar()
        //cy.get('#btnSalvar').click()
        demandas_associacao.clicarModalBTNOk()
        //cy.get('.modal-footer > .btn-primary').click()

        //validação de salvamento
        demandas_associacao.seletorRegiaoAdmin()
        //cy.get('#select2-cd_regiao_admin-container').click()
        demandas_associacao.seletorDropdown('RA-I - BRASILIA')
        //cy.get('.select2-results').find('li').contains('RA-I - BRASILIA').click({force: true})
        demandas_associacao.seletorCdEmpreendimento()
        //cy.get('#select2-cd_empreendimento-container').click()
        demandas_associacao.seletorDropdown('103 - Estagio de produção')
        //cy.get('.select2-results').find('li').contains('103 - Estagio de produção').click({force: true})
        demandas_associacao.clicarBotaoSalvar()
        //demandas_associacao.clicarBotaoPesquisar()
        //cy.get('#pesquisar').click()

        //validação da edição
        demandas_associacao.clicarPrimeiroBotaoEditar()
        //cy.get('a[title="Editar"]').first().click();
        demandas_associacao.clicarAba()
        //cy.get(':nth-child(2) > .text-center > .fas').click()
        demandas_associacao.seletorRegiaoAdmin()
        //cy.get('#select2-cd_regiao_admin-container').click()
        demandas_associacao.seletorDropdown('RA-III - TAGUATINGA')
        //cy.get('.select2-results').find('li').contains('RA-III - TAGUATINGA').click({force: true})
        demandas_associacao.seletorCdEmpreendimento()
        //cy.get('#select2-cd_empreendimento-container').click()
        demandas_associacao.seletorDropdown('7 - wwww')
        //cy.get('.select2-results').find('li').contains('7 - wwww').click({force: true})
        demandas_associacao.seletorDemanda()
        //cy.get('#select2-cd_demanda-container').click()
        demandas_associacao.seletorDropdown('AA - Autorização Ambiental nº 91/2022')
        //cy.get('.select2-results').find('li').contains('AA - Autorização Ambiental nº 91/2022').click({force: true})
        demandas_associacao.clicarBotaoAdicionar()
        //cy.get('#btnAdicionar').click()
        demandas_associacao.clicarBotaoAdicionar()
        //cy.get('#btnSalvar').click()
        demandas_associacao.clicarModalBTNOk()
        //cy.get('.modal-footer > .btn-primary').click()

        //validação de visualização
        demandas_associacao.seletorRegiaoAdmin()
        //cy.get('#select2-cd_regiao_admin-container').click()
        demandas_associacao.seletorDropdown('RA-I - BRASILIA')
        //cy.get('.select2-results').find('li').contains('RA-I - BRASILIA').click({force: true})
        demandas_associacao.seletorCdEmpreendimento()
        //cy.get('#select2-cd_empreendimento-container').click()
        demandas_associacao.seletorDropdown('103 - Estagio de produção')
        //cy.get('.select2-results').find('li').contains('103 - Estagio de produção').click({force: true})
        demandas_associacao.clicarBotaoPesquisar()
        //cy.get('#pesquisar').click()
        demandas_associacao.clicarPrimeiroBotaoVisualizar()
        //cy.get('a[title="Visualizar"]').first().click();
        demandas_associacao.botaoExcluirAssocDemand()
        //validação para excluir a associação
        //cy.get('#btn-delete-associacao-demanda').click()
        demandas_associacao.clicarModalBTNOk()
        //cy.get('.modal-footer > .btn-primary').click()
        demandas_associacao.clicarModalOk()
        //cy.get('.modal-footer > .btn').should('be.visible').and('contain.text', 'OK').click()
    })
})