/// <reference types="cypress" />

import estudos from "../../../support/pages/estudos";

describe('estudos', () => {
    beforeEach(() => {
        cy.visit('http://gla-homol.terracapnet.local')
        cy.viewport(1980, 1200)
       
          
    })
    it('teste Associação-consultar', () => {
        //abrindo a aba de estudos
        estudos.irParaGLA()
        estudos.login()
        estudos.validarTituloPendencia()
        //cy.get('h1').should('have.text', "Pendência")
        estudos.irAbaEstudos()
        //cy.get(':nth-child(4) > a > span').click()

        //validação dos campos na tela de estudos
        estudos.validarLabelEstudo()
        //cy.get('h1').should('have.text', "Estudo / Serviço")
        estudos.validarLabelRA()
        //cy.get('#form_filtro_geral > :nth-child(1) > :nth-child(1) > :nth-child(1) > .form-group > .control-label').should('have.text', "R.A")
        estudos.validarLabelEmpreendimento()
        //cy.get('#form_filtro_geral > :nth-child(1) > :nth-child(2) > .form-group > .control-label').should('have.text', "Empreendimento")
        estudos.validarLabelDemanda()
        //cy.get('#form_filtro_geral > :nth-child(1) > :nth-child(3) > .form-group > .control-label').should('have.text', "Demanda")
        estudos.validarLabelListaPendencia()
        //cy.get('#form_filtro_geral > :nth-child(2) > :nth-child(1) > .form-group > label').should('have.text', "Lista de Pendências")
        estudos.validarLabelTipo()
        //cy.get('#form_filtro_geral > :nth-child(2) > :nth-child(2) > .form-group > label').should('have.text', "Tipo")
        estudos.validarLabelNatureza()
        //cy.get('#form_filtro_geral > :nth-child(2) > :nth-child(3) > .form-group > label').should('have.text', "Natureza")
        estudos.validarLabelObjeto()
        //cy.get('#form_filtro_geral > :nth-child(2) > :nth-child(4) > .form-group > label').should('have.text', "Objeto")
        estudos.validarLabelDescricaoObjeto()
        //cy.get('#form_filtro_geral > :nth-child(3) > .col-md-12 > .form-group > .control-label').should('have.text', "Descrição do Objeto do Estudo/Serviço")
        estudos.validarLabelStatus()
        //cy.get(':nth-child(4) > :nth-child(1) > .form-group > label').should('have.text', "Status")
        estudos.validarLabelPrevisaoConclusao()
        //cy.get(':nth-child(4) > :nth-child(2) > :nth-child(1) > label').should('have.text', "Previsão de Conclusão do Estudo")
        estudos.validarLabelValorEstimado()
        //cy.get(':nth-child(5) > :nth-child(1) > :nth-child(1) > label').should('have.text', "Valor Estimado - (R$)")
        estudos.validarLabelDataElaboracao()
        //cy.get(':nth-child(5) > :nth-child(2) > :nth-child(1) > label').should('have.text', "Data Elaboração")
        estudos.validarLabelTitular()
        //cy.get(':nth-child(6) > :nth-child(1) > .form-group > label').should('have.text', "Titular ")
        estudos.validarLabelSuplente()
        //cy.get(':nth-child(6) > :nth-child(2) > .form-group > label').should('have.text', "Suplente ")
        estudos.validarLabelDadosContrato()
        //cy.get(':nth-child(2) > .box-header > .box-title').should('have.text', "Dados do Contrato")
        estudos.validarLabelNContrato()
        //cy.get('#form_filtro_contrato > :nth-child(1) > :nth-child(1) > .form-group > .control-label').should('have.text', "Número do Contrato")
        estudos.validarLabelAnoContrato()
        //cy.get('#form_filtro_contrato > :nth-child(1) > :nth-child(2) > .form-group > .control-label').should('have.text', "Ano do Contrato")
        estudos.validarLabelContratada()
        //cy.get('#form_filtro_contrato > :nth-child(1) > :nth-child(3) > .form-group > .control-label').should('have.text', "Contratada")
        estudos.validarLabelValorContratoInicial()
        //cy.get('#form_filtro_contrato > :nth-child(2) > :nth-child(1) > :nth-child(1) > label').should('have.text', "Valor do Contrato (inicial) - (R$)")
        estudos.validarLabelValorContratoFinal()
        //cy.get('#form_filtro_contrato > :nth-child(2) > :nth-child(2) > :nth-child(1) > label').should('have.text', "Valor do Contrato (final) - (R$)")
        estudos.validarLabelInicioVigenciaContrato()
        //cy.get('#form_filtro_contrato > :nth-child(2) > :nth-child(3) > :nth-child(1) > label').should('have.text', "Início da Vigência do Contrato")
        estudos.validarLabelFimVigenciaContrato()
        //cy.get('#form_filtro_contrato > :nth-child(2) > :nth-child(4) > :nth-child(1) > label').should('have.text', "Fim da Vigência do Contrato")
        estudos.validarLabelDescricaoObjetoContrato()
        //cy.get('#form_filtro_contrato > :nth-child(3) > .col-md-12 > .form-group > .control-label').should('have.text', "Descrição do Objeto do Contrato")
        estudos.validarLabelDadosOrdem()
        //cy.get(':nth-child(3) > .box-header > .box-title').should('have.text', "Dados da Ordem de Serviço da Empresa")
        estudos.validarLabelNumeroOS()
        //cy.get(':nth-child(3) > .box-body > .panel > #panel-body > #form_filtro_ordem_servico > .row > :nth-child(1) > .form-group > .control-label').should('have.text', "Número da OS")
        estudos.validarLabelAnoOS()
        //cy.get(':nth-child(3) > .box-body > .panel > #panel-body > #form_filtro_ordem_servico > .row > :nth-child(2) > .form-group > .control-label').should('have.text', "Ano da OS")
        estudos.validarLabelUnidadeResponsavelOS()
        //cy.get(':nth-child(3) > .box-body > .panel > #panel-body > #form_filtro_ordem_servico > .row > .col-md-6 > .form-group > .control-label').should('have.text', "Unidade Responsável pela OS")
        estudos.validarAriaLabelEmpreendimento()
        //cy.get('.sorting_asc').should('have.text', "Empreendimento")
        estudos.validarAriaLabelReferencia()
        //cy.get('[aria-label="Referência: Ordenar colunas de forma ascendente"]').should('have.text', "Referência")
        estudos.validarAriaLabelObjeto()
        //cy.get('[aria-label="Objeto: Ordenar colunas de forma ascendente"]').should('have.text', "Objeto")
        estudos.validarAriaLabelStatus()
        //cy.get('[aria-label="Status: Ordenar colunas de forma ascendente"]').should('have.text', "Status")
        estudos.validarAriaLabelContratoOS()
        //cy.get('[aria-label="Contrato | OS: Ordenar colunas de forma ascendente"]').should('have.text', "Contrato | OS")
        estudos.validarAriaLabelAcao()
        //cy.get('[aria-label="Ação: Ordenar colunas de forma ascendente"]').should('have.text', "Ação")

        //teste do botão limpar
        estudos.selecionarRA()
        // cy.get(':nth-child(1) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field').click()
        // cy.get('.select2-results').find('li').contains('RA-I - BRASILIA').click({force: true})

        estudos.limparFormularioPesquisa()
        // cy.wait(3000)
        // cy.get('[onclick="limparFormularioPesquisa()"]').click()

        //validação de campos na tela de novo cadastro
        estudos.botaoNovoCadastro()
        //cy.get('.btn-success').click()
        estudos.validarTextoNovoCadastro()
        //cy.get('.box-title').should('have.text', "Novo Cadastro")
        estudos.validarTextoReferencias()
        //cy.get("[onclick=\"toggleFormAccordion('rf')\"] > b").should('have.text', "Referências")
        estudos.validarTextoIncluirRequerimento()
        //cy.get('#form_estudo_servico > :nth-child(2) > :nth-child(7) > :nth-child(1)').should('have.text', "Incluir Requerimento")
        estudos.validarLabelCadastroRA()
        //cy.get(':nth-child(2) > :nth-child(1) > .form-group > .control-label').should('have.text', "R.A")
        estudos.validarLabelCadastroEmpreendimento()
        //cy.get('#form_requerimento > :nth-child(3) > .form-group > .control-label').should('have.text', "Empreendimento")
        estudos.validarLabelCadastroTipoRequerimento()
        //cy.get('#form_requerimento > :nth-child(4) > .form-group > .control-label').should('have.text', "Tipo Requerimento")
        estudos.validarLabelCadastroRequerimentos()
        //cy.get('#form_requerimento > :nth-child(5) > .form-group > label').should('have.text', "Requerimentos *")
        estudos.validarLabelCadastroRequerimentosReferenciados()
        //cy.get('#form_requerimento > :nth-child(7) > :nth-child(1)').should('have.text', "Requerimentos Referenciados")
        estudos.validarLabelCadastroRequerimento()
        //cy.get('#tabela-estudo-requerimento > thead > tr > .sorting_desc').should('have.text', "Requerimento")
        estudos.validarLabelCadastroIncluirExigencia()
        //cy.get(':nth-child(7) > :nth-child(4)').should('have.text', "Incluir Exigência")
        estudos.validarFormCadastroRA()
        //cy.get('#form_exigencia > :nth-child(1) > :nth-child(1) > .form-group > .control-label').should('have.text', "R.A")
        estudos.validarFormCadastroEmpreendimento()
        //cy.get('#form_exigencia > :nth-child(2) > .form-group > .control-label').should('have.text', "Empreendimento")
        estudos.validarFormCadastroDemanda()
        //cy.get('#form_exigencia > :nth-child(3) > .form-group > .control-label').should('have.text', "Demanda")
        estudos.validarFormCadastroExigencias()
        //cy.get('#form_exigencia > :nth-child(4) > .form-group > label').should('have.text', "Exigências *")
        estudos.validarFormCadastroExigenciasRef()
        //cy.get('#form_exigencia > :nth-child(6) > :nth-child(1)').should('have.text', "Exigências Referenciadas")
        estudos.validarTabelaCadastroN()
        //cy.get('#tabela-estudo-exigencia > thead > tr > .sorting_desc').should('have.text', "N°")
        estudos.validarTabelaCadastroDescricao()
        //cy.get('#tabela-estudo-exigencia > thead > tr > .sorting').should('have.text', "Descrição")
        estudos.validarTabelaCadastroAcao()
        //cy.get('#tabela-estudo-exigencia > thead > tr > .text-center').should('have.text', "Ação")
        estudos.validarLabelCadastroDadosGerais()
        //cy.get("[onclick=\"toggleFormAccordion('gr')\"] > b").should('have.text', "Dados Gerais")
        estudos.validarFormCadastroTipo()
        //cy.get('#form_dados_gerais > :nth-child(1) > .form-group > label').should('have.text', "Tipo*")
        estudos.validarFormCadastroNatureza()
        //cy.get('#form_dados_gerais > :nth-child(2) > .form-group > .control-label').should('have.text', "Natureza")
        estudos.validarLabelCadastroObjeto()
        //cy.get(':nth-child(3) > .control-label').should('have.text', "Objeto")
        estudos.validarFormCadastroDescricao()
        //cy.get('#form_dados_gerais > :nth-child(4) > .form-group > .control-label').should('have.text', "Descrição do Objeto do Estudo/Serviço")
        estudos.validarFormCadastroAreaPoligonal()
        //cy.get('#form_dados_gerais > :nth-child(5) > .form-group > .control-label').should('have.text', "Área da Poligonal de Estudo")
        estudos.validarFormCadastroStatus()
        //cy.get('#form_dados_gerais > :nth-child(6) > .form-group > .control-label').should('have.text', "Status")
        estudos.validarFormCadastroDescricaoStatus()
        //cy.get('#form_dados_gerais > :nth-child(7) > .form-group > .control-label').should('have.text', "Descrição do Status")
        estudos.validarFormCadastroOrgaoExterno()
        //cy.get('#form_dados_gerais > :nth-child(8) > .form-group > .control-label').should('have.text', "Órgão Externo avaliador")
        estudos.validarFormCadastroValorEstimado()
        //cy.get('#form_dados_gerais > :nth-child(9) > .form-group > .control-label').should('have.text', "Valor Estimado")
        estudos.validarFormCadastroProcessoSEI()
        //cy.get('#form_dados_gerais > :nth-child(10) > .form-group > label').should('have.text', "Processo SEI de Acompanhamento / Contratação")
        estudos.validarFormCadastroTitular()
        //cy.get(':nth-child(11) > .form-group > .control-label').should('have.text', "Titular")
        estudos.validarFormCadastroSuplente()
        //cy.get(':nth-child(12) > .form-group > .control-label').should('have.text', "Suplente")
        estudos.validarFormCadastroCaminhoDepart()
        //cy.get(':nth-child(13) > .form-group > .control-label').should('have.text', "Caminho no Depart")
        estudos.validarFormCadastroDataElaboracao()
        //cy.get(':nth-child(14) > .control-label').should('have.text', "Data de Elaboração")
        estudos.validarFormCadastroPrevisaoConclusaoEstudo()
        //cy.get(':nth-child(15) > .control-label').should('have.text', "Previsão de Conclusão do Estudo")
        estudos.validarFormCadastroDadosContrato()
        //cy.get("[onclick=\"toggleFormAccordion('ct')\"] > b").should('have.text', "Dados do Contrato")
        estudos.validarFormCadastro()
        //cy.get('#ct_plus').click()
        estudos.validarFormCadastroNumeroContrato()
        //cy.get('#form_contrato_gec > :nth-child(2) > .form-group > .control-label').should('have.text', "Numero do Contrato")
        estudos.validarFormCadastroAnoContrato()
        //cy.get('#form_contrato_gec > :nth-child(3) > .form-group > .control-label').should('have.text', "Ano do Contrato")
        estudos.validarFormCadastroContratada()
        //cy.get('#form_contrato_gec > :nth-child(5) > .form-group > .control-label').should('have.text', "Contratada")
        estudos.validarFormCadastroValorContratoInicial()
        //cy.get('#form_contrato_gec > :nth-child(6) > .form-group > .control-label').should('have.text', "Valor do Contrato (inicial)")
        estudos.validarFormCadastroValorContrato()
        //cy.get('#form_contrato_gec > :nth-child(7) > .form-group > .control-label').should('have.text', "Valor do Contrato (reajustado)")
        estudos.validarFormCadastroInicioVigenciaContrato()
        //cy.get('#form_contrato_gec > :nth-child(8) > .form-group > .control-label').should('have.text', "Início da Vigência do Contrato")
        estudos.validarFormCadastroFimVigenciaContrato()
        //cy.get('#form_contrato_gec > :nth-child(9) > .form-group > .control-label').should('have.text', "Fim da Vigência do Contrato")
        estudos.validarFormCadastroDescricaObjetoContrato()
        //cy.get(':nth-child(10) > .form-group > .control-label').should('have.text', "Descrição do Objeto do Contrato")
        estudos.validarFormCadastroDadosOrdemServico()
        //cy.get("[onclick=\"toggleFormAccordion('os')\"] > b").should('have.text', "Dados da Ordem de Serviço da Empresa")
        estudos.clicarBotaoMais()
        //cy.get('#os_plus').click()

        //validação de novo cadastro
        estudos.selecionarRegiaoAdmin()
        //cy.get('#select2-cd_regiao_admin_req-container').click()
        estudos.seletorDropdown('RA-I - BRASILIA')
        //cy.get('.select2-results').find('li').contains('RA-I - BRASILIA').click({force: true})
        estudos.selecionarEmpreendimento()
        //cy.get('#select2-cd_empreendimento_req-container > .select2-selection__clear').click()
        //cy.wait(3000)
        estudos.seletorDropdown('12 - Polos 06, 07, 08 - Projeto Orla - Beira Lago')
        //cy.get('.select2-results').find('li').contains('12 - Polos 06, 07, 08 - Projeto Orla - Beira Lago').click({force: true})
        estudos.selecionarTpRequerimento()
        //cy.get('#select2-tp_requerimento-container').click()
        estudos.seletorDropdown('Nova Permissão')
        //cy.get('.select2-results').find('li').contains('Nova Permissão').click({force: true})
        estudos.selecionarCdRequerimento()
        //cy.get('#select2-cd_requerimento-container > .select2-selection__clear').click()
        estudos.seletorDropdown('88 - LP - Licença Prévia - Ofício nº 6/1565 - ACJUR p/ ADASA')
        //cy.get('.select2-results').find('li').contains('88 - LP - Licença Prévia - Ofício nº 6/1565 - ACJUR p/ ADASA').click({force: true})
        estudos.clicarBotaoAdicionarRequerimento()
        //cy.get('#btnAdicionar_requerimento').click()
        estudos.selecionarRegiaoAdminExi()
        //cy.get('#select2-cd_regiao_admin_exi-container').click()
        estudos.seletorDropdown('RA-I - BRASILIA')
        //cy.get('.select2-results').find('li').contains('RA-I - BRASILIA').click({force: true})
        estudos.selecionarEmpreendimentoExi()
        //cy.get('#select2-cd_empreendimento_exi-container > .select2-selection__clear').click()
        estudos.seletorDropdown('12 - Polos 06, 07, 08 - Projeto Orla - Beira Lago')
        //cy.get('.select2-results').find('li').contains('12 - Polos 06, 07, 08 - Projeto Orla - Beira Lago').click({force: true})
        estudos.selecionarDemandaContainer()
        //cy.get('#select2-cd_demanda-container > .select2-selection__clear').click()
        estudos.seletorDropdown('LP nº 737/1998')
        //cy.get('.select2-results').find('li').contains('LP nº 737/1998').click({force: true})
        estudos.selecionarExigenciaContainer()
        //cy.get('#select2-cd_exigencia-container > .select2-selection__clear').click()
        estudos.seletorDropdown('82|1|----------------- ÇÇÇ Â ÂÂ')
        //cy.get('.select2-results').find('li').contains('82|1|----------------- ÇÇÇ Â ÂÂ').click({force: true})
        estudos.clicarBotaoAdicionarExigencia()
        //cy.get('#btnAdicionar_exigencia').click()
        estudos.selecionarTpEstudoContainer()
        //cy.get('#select2-tp_estudo-container').click()
        estudos.seletorDropdown('Obra/Serviço')
        //cy.get('.select2-results').find('li').contains('Obra/Serviço').click({force: true})
        estudos.selecionarTpNaturezaContainer()
        //cy.get('#select2-tp_natureza-container').click()
        estudos.seletorDropdown('Licitação')
        //cy.get('.select2-results').find('li').contains('Licitação').click({force: true})
        estudos.selecionarTpObjetoContainer()
        //cy.get('#select2-tp_objeto-container').click()
        estudos.seletorDropdown('Paisagismo')
        //cy.get('.select2-results').find('li').contains('Paisagismo').click({force: true})
        estudos.selecionarTpStatusContainer()
        //cy.get('#select2-tp_status-container').click()
        estudos.seletorDropdown('A licitar')
        //cy.get('.select2-results').find('li').contains('A licitar').click({force: true})
        estudos.selecionarCdPessoaTitularContainer()
        //cy.get('#select2-cd_pessoa_titular-container').click()
        estudos.seletorDropdown('PAULO CESAR COSTA')
        //cy.get('.select2-results').find('li').contains('PAULO CESAR COSTA').click({force: true})
        estudos.selecionarCdPessoaSuplenteContainer()
        //cy.get('#select2-cd_pessoa_suplente-container').click()
        estudos.seletorDropdown('LUCAS DIAS DE LIMA')
        //cy.get('.select2-results').find('li').contains('LUCAS DIAS DE LIMA').click({force: true})
        estudos.clicarBotaoSalvar()
        //cy.get('#btnSalvar').click()
        estudos.clicarBotaoContinuar()
        //cy.get('.modal-footer > .btn-primary').click()
        estudos.clicarBotaoOk()
        //cy.get('.modal-footer > .btn-danger').click()
        
        //validação do botão voltar
        estudos.clicarBotaoVoltar()
        //cy.get('[onclick="window.history.back()"]').click()
        //cy.get('[onclick="window.history.back()"]').click()

        //validação de salvamento
        estudos.selecionarPesTitular()
        cy.get(':nth-child(6) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field').click()
        estudos.seletorDropdown('PAULO CESAR COSTA')
        cy.get('.select2-results').find('li').contains('PAULO CESAR COSTA').click({force: true})
        estudos.selecionarPesSuplente()
        cy.get(':nth-child(6) > :nth-child(2) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field').click()
        estudos.seletorDropdown('LUCAS DIAS DE LIMA')
        cy.get('.select2-results').find('li').contains('LUCAS DIAS DE LIMA').click({force: true})
        estudos.botaoPesquisar()
        cy.get('#pesquisar').click()
        

        //validação da tela de edição
        estudos.clicarPrimeiroBotaoEditar()
        //cy.get('a[title="Editar"]').first().click()
        estudos.validarTituloEditar()
        //cy.get('.box-title').should('have.text', "Editar")
        //cy.wait(4000)
        estudos.seletorPessoaTitular()
        //cy.get('#select2-cd_pessoa_titular-container > .select2-selection__clear').click()
        //cy.wait(4000)
        estudos.seletorDropdown('NELSON ALVES LOUZEIRO JUNIOR')
        //cy.get('.select2-results').find('li').contains('NELSON ALVES LOUZEIRO JUNIOR').click({force: true})
        estudos.seletorPessoaSuplente()
        //cy.get('#select2-cd_pessoa_suplente-container > .select2-selection__clear').click()
        estudos.seletorDropdown('PEDRO RAFAEL MANDAI')
        //cy.get('.select2-results').find('li').contains('PEDRO RAFAEL MANDAI').click({force: true})
        estudos.clicarBotaoSalvar()
        //cy.get('#btnSalvar').click()
        estudos.clicarBotaoContinuar()
        //cy.get('.modal-footer > .btn-primary').click()
        estudos.clicarBotaoOk()
        //cy.get('.modal-footer > .btn-danger').click()
        cy.wait(6000)

        //validação de salvamento
        estudos.irAbaEstudos()
        //cy.get(':nth-child(4) > a > span').click()
        estudos.selecionarPesTitular()
        //cy.get(':nth-child(6) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field').click()
        estudos.seletorDropdown('NELSON ALVES LOUZEIRO JUNIOR')
        //cy.get('.select2-results').find('li').contains('NELSON ALVES LOUZEIRO JUNIOR').click({force: true})
        estudos.selecionarPesSuplente()
        //cy.get(':nth-child(6) > :nth-child(2) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field').click()
        estudos.seletorDropdown('PEDRO RAFAEL MANDAI')
        //cy.get('.select2-results').find('li').contains('PEDRO RAFAEL MANDAI').click({force: true})
        estudos.botaoPesquisar()
        //cy.get('#pesquisar').click()


        //validando o botão de excluir
        estudos.clicarPrimeiroBotaoExcluir()
        //cy.get('a[title="Excluir"]').first().click()
        estudos.clicarModalOk()
        //cy.get('.modal-footer > .btn').should('be.visible').and('contain.text', 'OK').click();
    })
})