/// <reference types="cypress" />

import estudos from "../../../support/pages/estudos";

describe('estudos', () => {
    beforeEach(() => {
        cy.visit('http://gla-homol.terracapnet.local')
        cy.viewport(1980, 1200)
    })

    it('teste Associação-consultar', () => {
        //abrindo a aba de estudos
        estudos.irParaGLA()
        estudos.login()
        estudos.validarTituloPendencia()
        estudos.irAbaEstudos()

        //validação dos campos na tela de estudos
        estudos.validarLabelEstudo()
        estudos.validarLabelRA()
        estudos.validarLabelEmpreendimento()
        estudos.validarLabelDemanda()
        estudos.validarLabelListaPendencia()
        estudos.validarLabelTipo()
        estudos.validarLabelNatureza()
        estudos.validarLabelObjeto()
        estudos.validarLabelDescricaoObjeto()
        estudos.validarLabelStatus()
        estudos.validarLabelPrevisaoConclusao()
        estudos.validarLabelValorEstimado()
        estudos.validarLabelDataElaboracao()
        estudos.validarLabelTitular()
        estudos.validarLabelSuplente()
        estudos.validarLabelDadosContrato()
        estudos.validarLabelNContrato()
        estudos.validarLabelAnoContrato()
        estudos.validarLabelContratada()
        estudos.validarLabelValorContratoInicial()
        estudos.validarLabelValorContratoFinal()
        estudos.validarLabelInicioVigenciaContrato()
        estudos.validarLabelFimVigenciaContrato()
        estudos.validarLabelDescricaoObjetoContrato()
        estudos.validarLabelDadosOrdem()
        estudos.validarLabelNumeroOS()
        estudos.validarLabelAnoOS()
        estudos.validarLabelUnidadeResponsavelOS()
        estudos.validarAriaLabelEmpreendimento()
        estudos.validarAriaLabelReferencia()
        estudos.validarAriaLabelObjeto()
        estudos.validarAriaLabelStatus()
        estudos.validarAriaLabelContratoOS()
        estudos.validarAriaLabelAcao()

        //teste do botão limpar
        estudos.selecionarRA()
        estudos.limparFormularioPesquisa()

        //validação de campos na tela de novo cadastro
        estudos.botaoNovoCadastro()
        estudos.validarTextoNovoCadastro()
        estudos.validarTextoReferencias()
        estudos.validarTextoIncluirRequerimento()
        estudos.validarLabelCadastroRA()
        estudos.validarLabelCadastroEmpreendimento()
        estudos.validarLabelCadastroTipoRequerimento()
        estudos.validarLabelCadastroRequerimentos()
        estudos.validarLabelCadastroRequerimentosReferenciados()
        estudos.validarLabelCadastroRequerimento()
        estudos.validarLabelCadastroIncluirExigencia()
        estudos.validarFormCadastroRA()
        estudos.validarFormCadastroEmpreendimento()
        estudos.validarFormCadastroDemanda()
        estudos.validarFormCadastroExigencias()
        estudos.validarFormCadastroExigenciasRef()
        estudos.validarTabelaCadastroN()
        estudos.validarTabelaCadastroDescricao()
        estudos.validarTabelaCadastroAcao()
        estudos.validarLabelCadastroDadosGerais()
        estudos.validarFormCadastroTipo()
        estudos.validarFormCadastroNatureza()
        estudos.validarLabelCadastroObjeto()
        estudos.validarFormCadastroDescricao()
        estudos.validarFormCadastroAreaPoligonal()
        estudos.validarFormCadastroStatus()
        estudos.validarFormCadastroDescricaoStatus()
        estudos.validarFormCadastroOrgaoExterno()
        estudos.validarFormCadastroValorEstimado()
        estudos.validarFormCadastroProcessoSEI()
        estudos.validarFormCadastroTitular()
        estudos.validarFormCadastroSuplente()
        estudos.validarFormCadastroCaminhoDepart()
        estudos.validarFormCadastroDataElaboracao()
        estudos.validarFormCadastroPrevisaoConclusaoEstudo()
        estudos.validarFormCadastroDadosContrato()
        estudos.validarFormCadastro()
        estudos.validarFormCadastroNumeroContrato()
        estudos.validarFormCadastroAnoContrato()
        estudos.validarFormCadastroContratada()
        estudos.validarFormCadastroValorContratoInicial()
        estudos.validarFormCadastroValorContrato()
        estudos.validarFormCadastroInicioVigenciaContrato()
        estudos.validarFormCadastroFimVigenciaContrato()
        estudos.validarFormCadastroDescricaObjetoContrato()
        estudos.validarFormCadastroDadosOrdemServico()
        estudos.clicarBotaoMais()

        //validação de novo cadastro
        estudos.selecionarRegiaoAdmin()
        estudos.seletorDropdown('RA-I - BRASILIA')
        estudos.selecionarEmpreendimento()
        estudos.seletorDropdown('12 - Polos 06, 07, 08 - Projeto Orla - Beira Lago')
        estudos.selecionarTpRequerimento()
        estudos.seletorDropdown('Nova Permissão')
        estudos.selecionarCdRequerimento()
        estudos.seletorDropdown('88 - LP - Licença Prévia - Ofício nº 6/1565 - ACJUR p/ ADASA')
        estudos.clicarBotaoAdicionarRequerimento()
        estudos.selecionarRegiaoAdminExi()
        estudos.seletorDropdown('RA-I - BRASILIA')
        estudos.selecionarEmpreendimentoExi()
        estudos.seletorDropdown('12 - Polos 06, 07, 08 - Projeto Orla - Beira Lago')
        estudos.selecionarDemandaContainer()
        estudos.seletorDropdown('LP nº 737/1998')
        estudos.selecionarExigenciaContainer()
        estudos.seletorDropdown('82|1|----------------- ÇÇÇ Â ÂÂ')
        estudos.clicarBotaoAdicionarExigencia()
        estudos.selecionarTpEstudoContainer()
        estudos.seletorDropdown('Obra/Serviço')
        estudos.selecionarTpNaturezaContainer()
        estudos.seletorDropdown('Licitação')
        estudos.selecionarTpObjetoContainer()
        estudos.seletorDropdown('Paisagismo')
        estudos.selecionarTpStatusContainer()
        estudos.seletorDropdown('A licitar')
        estudos.selecionarCdPessoaTitularContainer()
        estudos.seletorDropdown('PAULO CESAR COSTA')
        estudos.selecionarCdPessoaSuplenteContainer()
        estudos.seletorDropdown('LUCAS DIAS DE LIMA')
        estudos.clicarBotaoSalvar()
        estudos.clicarBotaoContinuar()
        estudos.clicarBotaoOk()

        //validação do botão voltar
        estudos.clicarBotaoVoltar()

        //validação de salvamento
        estudos.selecionarPesTitular()
        estudos.seletorDropdown('PAULO CESAR COSTA')
        estudos.selecionarPesSuplente()
        estudos.seletorDropdown('LUCAS DIAS DE LIMA')
        estudos.botaoPesquisar()

        //validação da tela de edição
        estudos.clicarPrimeiroBotaoEditar()
        estudos.validarTituloEditar()
        estudos.seletorPessoaTitular()
        estudos.seletorDropdown('NELSON ALVES LOUZEIRO JUNIOR')
        estudos.seletorPessoaSuplente()
        estudos.seletorDropdown('PEDRO RAFAEL MANDAI')
        estudos.clicarBotaoSalvar()
        estudos.clicarBotaoContinuar()
        estudos.clicarBotaoOk()
        cy.wait(6000)

        //validação de salvamento
        estudos.irAbaEstudos()
        estudos.selecionarPesTitular()
        estudos.seletorDropdown('NELSON ALVES LOUZEIRO JUNIOR')
        estudos.selecionarPesSuplente()
        estudos.seletorDropdown('PEDRO RAFAEL MANDAI')
        estudos.botaoPesquisar()

        //validando o botão de excluir
        estudos.clicarPrimeiroBotaoExcluir()
        estudos.clicarModalOk()
    })
})
