
/// <reference types="cypress" />

import pendencias from "../../../support/pages/pendencias";

describe('pendência', () => {
    beforeEach(() => {
        cy.visit('http://gla-homol.terracapnet.local')
        cy.viewport(1980, 1200)
       
          
    })
    it('teste cadastrar pendência no empreendimento', () => {
        
        pendencias.irParaGLA()
        pendencias.login()
        // cy.get(':nth-child(2) > .form-control').type('C9020840')
        // cy.get(':nth-child(3) > .form-control').type('welcome_1')
        // cy.get('.btn').click()


        pendencias.validarTituloPendencia()
        cy.get('h1').should('have.text', "Pendência")
        pendencias.clicarAbaPendencia()
        cy.get('.sidebar-menu > :nth-child(1) > a > span').click()
        pendencias.validarLabelEmpreendedorResponsavel()
        cy.get(':nth-child(1) > :nth-child(1) > .form-group > label').should('have.text', "Empreendedor Responsável ")
        pendencias.validarLabelEmpreendimento()
        cy.get(':nth-child(1) > :nth-child(2) > .form-group > label').should('have.text', "Empreendimento ")
        pendencias.validarLabelPrioridade()
        cy.get(':nth-child(1) > :nth-child(3) > .form-group > label').should('have.text', "Prioridade ")
        pendencias.validarLabelListaPendencias()
        cy.get(':nth-child(2) > :nth-child(1) > .form-group > label').should('have.text', "Lista de Pendências ")
        pendencias.validarLabelCategoria()
        cy.get(':nth-child(2) > :nth-child(2) > .form-group > label').should('have.text', "Categoria ")
        pendencias.validarLabelResumo()
        cy.get(':nth-child(3) > .form-group > .control-label').should('have.text', "Resumo")
        pendencias.validarLabelUnidadeInterna()
        cy.get(':nth-child(4) > .form-group > label').should('have.text', "Unidade Interna ")
        pendencias.validarLabelStausPendencia()
        cy.get(':nth-child(3) > :nth-child(1) > .form-group > label').should('have.text', "Status da Pendência")
        pendencias.validarLabelProvidencias()
        cy.get(':nth-child(3) > :nth-child(2) > .form-group > .control-label').should('have.text', "Providências")
        pendencias.validarLabelExigeContratacao()
        cy.get(':nth-child(3) > :nth-child(3) > .form-group > label').should('have.text', "Exige Contratação?")
        pendencias.validarLabelPrevisaoCumprimento()
        cy.get(':nth-child(4) > :nth-child(1) > :nth-child(1) > .control-label').should('have.text', "Previsão de Cumprimento")
        pendencias.validarLabelDataLimite()
        cy.get(':nth-child(4) > :nth-child(2) > :nth-child(1) > .control-label').should('have.text', "Data Limite")
        pendencias.validarLabelTitular()
        cy.get(':nth-child(4) > :nth-child(3) > .form-group > label').should('have.text', "Titular ")
        pendencias.validarLabelPeriodoLimite()
        cy.get(':nth-child(5) > :nth-child(1) > :nth-child(1) > .control-label').should('have.text', "Período Dias Restantes (data limite)")
        pendencias.validarLabelPeriodoCumprimento()
        cy.get(':nth-child(5) > :nth-child(2) > :nth-child(1) > .control-label').should('have.text', "Período Dias Restantes (previsão de cumprimento)")
        pendencias.validarLabelSuplente()
        cy.get(':nth-child(5) > :nth-child(3) > .form-group > label').should('have.text', "Suplente ")
        pendencias.validarALabelEmpreendedorResponsavel()
        cy.get('.sorting_asc').should('have.text', "Empreendedor Responsável")
        pendencias.validarALabelEmpreendimento()
        cy.get('[aria-label="Empreendimento: Ordenar colunas de forma ascendente"]').should('have.text', "Empreendimento")
        pendencias.validarALabelPrioridade()
        cy.get('[aria-label="Prioridade: Ordenar colunas de forma ascendente"]').should('have.text', "Prioridade")
        pendencias.validarALabelListaPendencia()
        cy.get('[aria-label="Lista de Pendências: Ordenar colunas de forma ascendente"]').should('have.text', "Lista de Pendências")
        pendencias.validarALabelCategoria()
        cy.get('[aria-label="Categoria: Ordenar colunas de forma ascendente"]').should('have.text', "Categoria")
        pendencias.validarALabelResumo()
        cy.get('[aria-label="Resumo: Ordenar colunas de forma ascendente"]').should('have.text', "Resumo")
        pendencias.validarALabelExigenciaVinculada()
        cy.get('[aria-label="Exigência Vinculada: Ordenar colunas de forma ascendente"]').should('have.text', "Exigência Vinculada")
        pendencias.validarALabelUnidadeInterna()
        cy.get('[aria-label="Unidade Interna: Ordenar colunas de forma ascendente"]').should('have.text', "Unidade Interna")
        pendencias.validarALabelProcSeiAcompanhamento()
        cy.get('[aria-label="Proc Sei de Acompanhamento: Ordenar colunas de forma ascendente"]').should('have.text', "Proc Sei de Acompanhamento")
        pendencias.validarALabelStatusPendencia()
        cy.get('[aria-label="Status da Pendência: Ordenar colunas de forma ascendente"]').should('have.text', "Status da Pendência")
        pendencias.validarALabelProvidencia()
        cy.get('[aria-label="Providência: Ordenar colunas de forma ascendente"]').should('have.text', "Providência")
        pendencias.validarALabelExigeContratacao()
        cy.get('[aria-label="Exige Contratação?: Ordenar colunas de forma ascendente"]').should('have.text', "Exige Contratação?")
        pendencias.validarALabelPrevisaoCumprimento()
        cy.get('[aria-label="Previsão de Cumprimento: Ordenar colunas de forma ascendente"]').should('have.text', "Previsão de Cumprimento")
        pendencias.validarALabelDiasCumprimento()
        cy.get('[aria-label="Dias Restantes (Previsão de Cumprimento): Ordenar colunas de forma ascendente"]').should('have.text', "Dias Restantes (Previsão de Cumprimento)")
        pendencias.validarALabelDataLimite()
        cy.get('[aria-label="Data Limite: Ordenar colunas de forma ascendente"]').should('have.text', "Data Limite")
        pendencias.validarALabelDiasLimite()
        cy.get('[aria-label="Dias Restantes (Data Limite): Ordenar colunas de forma ascendente"]').should('have.text', "Dias Restantes (Data Limite)")
        pendencias.clicarBotaoCadastrarEditar()
        cy.get('.btn-success').click()
        pendencias.selecionarCdEmpreendimento()
        cy.get('#select2-cd_empreendimento-container').click()
        pendencias.dropdownGLA('4 - Empreendimento XPTO 5 ')
        cy.get('.select2-results').find('li').contains('4 - Empreendimento XPTO 5 ').click({ force: true});
        pendencias.pesquisarPendencia()
        cy.get('#pesquisarPendencias').click()
        pendencias.validarTituloPendencia()
        cy.get('h1').should('have.text', "Pendência")
        pendencias.validarTituloCadastrarEditar()
        cy.get('#pendencia > .box > .box-header > .box-title').should('have.text', "Cadastrar/Editar")
        pendencias.validarAdListaPendencia()
        cy.get('.panel-body > .panel-footer > .btn-toolbar > .btn-success').should('have.text', "Adicionar Lista de Pendências")
        pendencias.clicarBtn()
        cy.get('.content > :nth-child(3) > .box-header > .box-tools > .btn > .fa').click()

        pendencias.criarLinhas()
        for(var i = 0; i < 14; i++){
            cy.get('#pendenciaTodas3283 > .panel-footer > .btn-toolbar > .btn-primary').click()
            cy.wait(1000)
        }
        pendencias.adicionar1Dado()
        cy.get(':nth-child(1) > :nth-child(2) > div > a > .fa').click()
        cy.wait(2000)
        pendencias.adicionar2Dado('teste')
        cy.get('#cke_1_contents iframe').its('0.contentDocument.body').should('not.be.empty').then(cy.wrap).find('p').click().type('teste');
        pendencias.adicionar3Dado()
        cy.get('#modal-alteracao-resumo > .modal-dialog > .modal-content > .modal-footer > #botao-editar').click()
        pendencias.adicionar4Dado()
        cy.get(':nth-child(2) > :nth-child(3) > a > .fa').click()
        cy.wait(2000)
        pendencias.selecionarCdDemanda()
        cy.get('#select2-cd_demanda-container').click()
        cy.wait(2000)
        pendencias.selecionarDado()
        cy.get(':nth-child(3) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered').click()
        pendencias.dropdownGLA('Informativo')
        cy.get('.select2-results').find('li').contains('Informativo').click({force: true})
        pendencias.clicarBotaoEditar()
        cy.get(':nth-child(2) > #botao-editar').click()
        pendencias.clicarExigencia()
        cy.get('.exigencia').click()
        pendencias.clicarSegBotaoEditar()
        cy.get(':nth-child(4) > #botao-editar').click()
        pendencias.adicionar5Dado()
        cy.get(':nth-child(3) > :nth-child(4) > a').click()
        pendencias.selecionarOrgaoUnidadeInterna()
        cy.get('#select2-cd_orgao_unidade_interna_pendencia-container').click()
        pendencias.dropdownGLA('ACJUR - ADVOCACIA E CONSULTORIA JURIDICA ')
        cy.get('.select2-results').find('li').contains('ACJUR - ADVOCACIA E CONSULTORIA JURIDICA ').click({force: true})
        pendencias.adicionarUnidadeInterna()
        cy.get('#add_unidade_interna_pendencia').click()
        cy.wait(1000)
        pendencias.clicarPrimeiroBotao()
        cy.get('.col-md-12 > .btn-primary').click()
        cy.wait(1000)
        pendencias.adicionar5Dado()
        cy.get(':nth-child(4) > :nth-child(5) > a > .fa').click()
        cy.wait(1000)
        pendencias.digitarOrgaoProcessoSei('11111')
        cy.get('#cd_orgao_processo_sei').type('11111')
        cy.wait(1000)
        pendencias.DigitarNumeroProcessoSei('11111111')
        cy.get('#nr_processo_sei').type('11111111')
        cy.wait(1000)
        pendencias.digitarAnoProcessoSei('1111')
        cy.get('#aa_processo_sei').type('1111')
        cy.wait(4000)
        pendencias.modalEditar()
        cy.get('#modal-alteracao-sei > .modal-dialog > .modal-content > .modal-footer > #botao-editar').click()
        cy.wait(1000)
        pendencias.selecionar()
        cy.get(':nth-child(5) > :nth-child(6) > select').select('2911')
        pendencias.adicionar6Dado()
        cy.get(':nth-child(6) > :nth-child(7) > div > a > .fa').click()
        pendencias.digitarEmParagrafo('teste')
        cy.get('#cke_2_contents > .cke_wysiwyg_frame').its('0.contentDocument.body').should('not.be.empty').then(cy.wrap).find('p').click().type('teste')
        pendencias.alterarModalProvidencia()
        cy.get('#modal-alteracao-providencia > .modal-dialog > .modal-content > .modal-footer > #botao-editar').click()
        pendencias.adicionar7Dado()
        cy.get(':nth-child(7) > :nth-child(8) > select').select('1')

        const dataBrasileira = '01/01/2024';

        const [dia, mes, ano] = dataBrasileira.split('/');

        const dataFormatoCypress = `${ano}-${mes}-${dia}`; 

        pendencias.adicionar7Dado()
        cy.get(':nth-child(8) > :nth-child(9) > a > .fa').click()
        pendencias.digitarDataPrevisaoCumprimento()
        cy.get('#dt_previsao_cumprimento').type(dataFormatoCypress)// Digita no campo
        pendencias.alterarModalCumprimento()
        cy.get('#modal-alteracao-cumprimento > .modal-dialog > .modal-content > .modal-footer > #botao-editar').click()
        pendencias.ignorarErro()
        cy.on('uncaught:exception', (err, runnable) => {
            return false; // Ignora o erro para que o teste continue
          });

        const DataBrasileira = '01/01/2026';
        const [Dia, Mes, Ano] = DataBrasileira.split('/');
        const DataFormatoCypress = `${Ano}-${Mes}-${Dia}`;

        pendencias.adicionar8Dado()
        cy.get(':nth-child(9) > :nth-child(11) > a > .fa').click()
        pendencias.digitarDataLimite()
        cy.get('#dt_limite').type(DataFormatoCypress)
        pendencias.alterarModalLimite()
        cy.get('#modal-alteracao-limite > .modal-dialog > .modal-content > .modal-footer > #botao-editar').click()
        pendencias.ignorarErro()
        cy.on('uncaught:exception', (err, runnable) => {
            return true; // Ignora o erro para que o teste continue
          });
        pendencias.irAba()
        cy.get('.sidebar-menu > :nth-child(1) > a > span').click()
        pendencias.seletorEmpreendimento()
        cy.get(':nth-child(1) > :nth-child(2) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field').click()
        pendencias.dropdownGLA('4 - Empreendimento XPTO 5 ')
        cy.get('.select2-results').find('li').contains('4 - Empreendimento XPTO 5 ').click({force: true})
        pendencias.clicarBotaoPesquisar()
        cy.get('#pesquisar').click()
        cy.wait(6000)
        pendencias.clicarLimparPesquisa()
        cy.get('[onclick="limpaPesquisa()"]').click({force: true})
        pendencias.seletorEmpreendimento()
        cy.get(':nth-child(1) > :nth-child(2) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field').click()
        pendencias.dropdownGLA('4 - Empreendimento XPTO 5 ')
        cy.get('.select2-results').find('li').contains('4 - Empreendimento XPTO 5 ').click({ force: true});
        pendencias.clicarBotaoPesquisar()
        cy.get('#pesquisar').click()
        cy.wait(4000)
        pendencias.gerarRelatorioPDF()
        cy.get('#gerarRelatorioPDF').click({force: true})
        cy.wait(10000)
        pendencias.clicarBotaoCadastrarEditar()
        cy.get('.btn-success').click()
        pendencias.selecionarCdEmpreendimento()
        cy.get('#select2-cd_empreendimento-container').click()
        pendencias.dropdownGLA('4 - Empreendimento XPTO 5 ')
        cy.get('.select2-results').find('li').contains('4 - Empreendimento XPTO 5 ').click({ force: true});
        pendencias.clicarPesquisarPendencias()
        cy.get('#pesquisarPendencias').click()
        pendencias.clicarPrimeiro()
        cy.get('.content > :nth-child(3) > .box-header > .box-tools > .btn > .fa').click()
        pendencias.clicarTodasPendencias()
        cy.get('#pendenciaTodas3283 > .panel-footer > .btn-toolbar > .btn-danger').click()
        pendencias.clicarModal()
        cy.get('.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-primary').click()
        cy.wait(3000)
        pendencias.clicarBtnSucess()
        cy.get('.btn-toolbar > .btn-success').click()
        pendencias.clicarLista()
        cy.get('#lista_chk_cd_3283').click()
        pendencias.clicarModalVinculoPendencia()
        cy.get('#modal-vinculo-pendencia > .modal-dialog > .modal-content > .modal-footer > #botao-editar').click()
    })
})
