export const ELEMENTS = {

    //login
    campoUsuario: ':nth-child(2) > .form-control',
    campoSenha: ':nth-child(3) > .form-control',
    botaoLogin: '.btn',
    tituloPendencia:'h1',
    abaPendencia: '.sidebar-menu > :nth-child(1) > a > span',
    labelEmpreendedorResponsavel: ':nth-child(1) > :nth-child(1) > .form-group > label',
    labelEmpreendimento: ':nth-child(1) > :nth-child(2) > .form-group > label',
    labelPrioridade: ':nth-child(1) > :nth-child(3) > .form-group > label',
    labelListaPendencias: ':nth-child(2) > :nth-child(1) > .form-group > label',
    labelCategoria: ':nth-child(2) > :nth-child(2) > .form-group > label',
    labelResumo: ':nth-child(3) > .form-group > .control-label',
    labelUnidadeInterna: ':nth-child(4) > .form-group > label',
    labelStatusPendencia: ':nth-child(3) > :nth-child(1) > .form-group > label',
    labelProvidencias: ':nth-child(3) > :nth-child(2) > .form-group > .control-label',
    labelExigeContratacao: ':nth-child(3) > :nth-child(3) > .form-group > label',
    labelPrevisaoCumprimento: ':nth-child(4) > :nth-child(1) > :nth-child(1) > .control-label',
    labelDataLimite: ':nth-child(4) > :nth-child(2) > :nth-child(1) > .control-label',
    labelTitular: ':nth-child(4) > :nth-child(3) > .form-group > label',
    labelPeriodoLimite: ':nth-child(5) > :nth-child(1) > :nth-child(1) > .control-label',
    labelPeriodoCumprimento: ':nth-child(5) > :nth-child(2) > :nth-child(1) > .control-label',
    labelSuplente: ':nth-child(5) > :nth-child(3) > .form-group > label',
    aLabelEmpreendedorResponsavel: '.sorting_asc',
    aLabelEmpreendimento: '[aria-label="Empreendimento: Ordenar colunas de forma ascendente"]',
    aLabelPrioridade: '[aria-label="Prioridade: Ordenar colunas de forma ascendente"]',
    aLabelListaPendencia: '[aria-label="Lista de Pendências: Ordenar colunas de forma ascendente"]',
    aLabelCategoria: '[aria-label="Categoria: Ordenar colunas de forma ascendente"]',
    aLabelResumo: '[aria-label="Resumo: Ordenar colunas de forma ascendente"]',
    aLabelExigenciaVinculada: '[aria-label="Exigência Vinculada: Ordenar colunas de forma ascendente"]',
    aLabelUnidadeInterna: '[aria-label="Unidade Interna: Ordenar colunas de forma ascendente"]',
    aLabelProcSeiAcompanhamento: '[aria-label="Proc Sei de Acompanhamento: Ordenar colunas de forma ascendente"]',
    aLabelStatusPendencia: '[aria-label="Status da Pendência: Ordenar colunas de forma ascendente"]',
    aLabelProvidencia: '[aria-label="Providência: Ordenar colunas de forma ascendente"]',
    aLabelExigeContratacao: '[aria-label="Exige Contratação?: Ordenar colunas de forma ascendente"]',
    aLabelPrevisaoCumprimento: '[aria-label="Previsão de Cumprimento: Ordenar colunas de forma ascendente"]',
    aLabelDiasCumprimento: '[aria-label="Dias Restantes (Previsão de Cumprimento): Ordenar colunas de forma ascendente"]',
    aLabelDataLimite: '[aria-label="Data Limite: Ordenar colunas de forma ascendente"]',
    aLabelDiasLimite: '[aria-label="Dias Restantes (Data Limite): Ordenar colunas de forma ascendente"]',
    botaoCadastrarEditar: '.btn-success',
    pendenciaTodasBtn: '#pendenciaTodas3283 > .panel-footer > .btn-toolbar > .btn-primary',
    adicionarResumo: ':nth-child(2) > :nth-child(2) > div > a > .fa',
    iframeAdicionar2Dado: '#cke_1_contents iframe',
    btnAdicionar3Dado: '#modal-alteracao-resumo > .modal-dialog > .modal-content > .modal-footer > #botao-editar',
    btnAdicionar4Dado: ':nth-child(2) > :nth-child(3) > a > .fa',
    cdDemandaContainer: '#select2-cd_demanda-container',
    selecionarDadoContainer: ':nth-child(3) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered',
    btnEditar: ':nth-child(2) > #botao-editar',
    btnExigencia: ':nth-child(1) > .sorting_1 > .exigencia',
    btnSegEditar: ':nth-child(4) > #botao-editar',
    btnAdicionar5Dado: ':nth-child(3) > :nth-child(4) > a',
    cdOrgaoUnidadeInternaContainer: '#select2-cd_orgao_unidade_interna_pendencia-container',
    btnAdicionarUnidadeInterna: '#add_unidade_interna_pendencia',
    btnPrimeiro: '.col-md-12 > .btn-primary',
    inputOrgaoProcessoSei: '#cd_orgao_processo_sei',
    inputNumeroProcessoSei: '#nr_processo_sei',
    inputAnoProcessoSei: '#aa_processo_sei',
    btnModalEditar: '#modal-alteracao-sei > .modal-dialog > .modal-content > .modal-footer > #botao-editar',
    select2911: ':nth-child(5) > :nth-child(6) > select',
    btnAdicionar6Dado: ':nth-child(6) > :nth-child(7) > div > a > .fa',
    btnAdicionar9Dado:':nth-child(4) > :nth-child(5) > a > .fa',
    iframeDigitarParagrafo: '#cke_2_contents > .cke_wysiwyg_frame',
    btnAlterarModalProvidencia: '#modal-alteracao-providencia > .modal-dialog > .modal-content > .modal-footer > #botao-editar',
    select1: ':nth-child(7) > :nth-child(8) > select',
    inputDataPrevisaoCumprimento: '#dt_previsao_cumprimento',
    btnAlterarModalCumprimento: '#modal-alteracao-cumprimento > .modal-dialog > .modal-content > .modal-footer > #botao-editar',
    btnAdicionar8Dado: ':nth-child(9) > :nth-child(11) > a > .fa',
    inputDataLimite: '#dt_limite',
    btnAlterarModalLimite: '#modal-alteracao-limite > .modal-dialog > .modal-content > .modal-footer > #botao-editar',
    abaPendencia2: '.sidebar-menu > :nth-child(1) > a > span',
    inputSeletorEmpreendimento: ':nth-child(1) > :nth-child(2) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    dropdownGLAItem: '.select2-results li:contains("4 - Empreendimento XPTO 5 ")',
    btnPesquisar: '#pesquisar',
    btnLimparPesquisa: '[onclick="limpaPesquisa()"]',
    btnGerarRelatorioPDF: '#gerarRelatorioPDF',
    btnPesquisarPendencias: '#pesquisarPendencias',
    btnPrimeiro1: '.content > :nth-child(3) > .box-header > .box-tools > .btn > .fa',
    btnTodasPendencias: '#pendenciaTodas3283 > .panel-footer > .btn-toolbar > .btn-danger',
    btnModal: '.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-primary',
    btnSucess: '.panel-body > .panel-footer > .btn-toolbar > .btn-success',
    chkLista: '#lista_chk_cd_3283',
    btnModalVinculoPendencia: '#modal-vinculo-pendencia > .modal-dialog > .modal-content > .modal-footer > #botao-editar',
}
