export const ELEMENTS = {

    //login
    campoUsuario: ':nth-child(2) > .form-control',
    campoSenha: ':nth-child(3) > .form-control',
    botaoLogin: '.btn',
    abaEmpreendimento: '.sidebar-menu > :nth-child(2) > a > span',
    tituloPesquisar:'.box-title',
    labelRA:':nth-child(1) > :nth-child(1) > .form-group > label',
    labelEmpreendimento:'.col-md-6 > .form-group > label',
    labelTipo:':nth-child(1) > :nth-child(3) > .form-group > label',
    labelPrioridade:':nth-child(2) > :nth-child(1) > .form-group > label',
    labelTitular:':nth-child(2) > :nth-child(2) > .form-group > label',
    labelSuplente:':nth-child(2) > :nth-child(3) > .form-group > label',
    labelEmpreendedorResponsavel:'.col-md-8 > .form-group > label',
    labelArquivado:':nth-child(3) > :nth-child(2) > .form-group > label',
    labelConcluido:':nth-child(3) > :nth-child(3) > .form-group > label',
    labelPossuiExigencia:'.col-md-5 > .form-group > label',
    labelPossuiRequerimento:':nth-child(4) > .col-md-3 > .form-group > label',
    labelPossuiLicenca:':nth-child(4) > .col-md-4 > .form-group > label',
    ariaLabelRA:'.sorting_asc',
    ariaLabelEmpreendimento:'[aria-label="Empreendimento: Ordenar colunas de forma ascendente"]',
    ariaLabelTipo:'[aria-label="Tipo: Ordenar colunas de forma ascendente"]',
    ariaLabelEmpreendedorResponsavel:'[aria-label="Empreendedor Responsável: Ordenar colunas de forma ascendente"]',
    ariaLabelPrioridade:'[aria-label="Prioridade: Ordenar colunas de forma ascendente"]',
    ariaLabelTitular:'[aria-label="Titular: Ordenar colunas de forma ascendente"]',
    ariaLabelArquivado:'[aria-label="Arquivado: Ordenar colunas de forma ascendente"]',
    ariaLabelAcao:'[aria-label="Ação: Ordenar colunas de forma ascendente"]',
    seletorRA: ':nth-child(1) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    dropdownGLA: '.select2-results',
    seletorEmpreendimento:'.col-md-6 > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    seletorTipo:':nth-child(1) > :nth-child(3) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    seletorPrioridade:':nth-child(2) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    seletorTitular:':nth-child(2) > :nth-child(2) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    seletorSuplente:':nth-child(2) > :nth-child(3) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    seletorEmpreendedorResponsavel:'.col-md-8 > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search',
    seletorArquivado:'#select2-fl_arquivado-container',
    seletorConcluido:'#select2-fl_concluido-container',
    seletorPossuiExigencia:'#select2-fl_exigencia_cumprir-container',
    seletorPossuiRequerimento:'.col-md-3 > .form-group > .select2-container > .selection > .select2-selection > #select2-fl_req_analise-container',
    seletorPossuiLicenca:'.col-md-4 > .form-group > .select2-container > .selection > .select2-selection > #select2-fl_req_analise-container',
    botaoLimpar: '[onclick="limpaPesquisa()"]',
    botaoNovoCadastro:'.btn-success',
    labelCadastroNovo: '.box-title',
    labelCadastroRA:':nth-child(5) > :nth-child(1) > .form-group > label' ,
    labelCadastroProcesSEIEmpreend: ':nth-child(5) > :nth-child(2) > .form-group > label',
    labelCadastroTipo: ':nth-child(5) > :nth-child(3) > .form-group > label',
    labelCadastroEmpreend:':nth-child(6) > .col-md-8 > .form-group > label' ,
    labelCadastroPrioridade:':nth-child(6) > .col-md-4 > .form-group > label' ,
    labelCadastroNumeroURB:':nth-child(7) > :nth-child(1) > .form-group > label' ,
    labelCadastroNumeroNGB: ':nth-child(7) > :nth-child(2) > .form-group > label',
    labelCadastroNumeroMDE: ':nth-child(7) > :nth-child(3) > .form-group > label',
    labelCadastroTitular: ':nth-child(8) > .col-md-8 > .form-group > label',
    labelCadastroArquivado: 'input[name="fl_arquivado"]',
    labelCadastroConcluido: 'input[name="fl_concluido"]',
    labelCadastroSuplente: ':nth-child(9) > :nth-child(1) > .form-group > label',
    labelCadastroEmpreendedorResponsavel:':nth-child(9) > :nth-child(2) > .form-group > label' ,
    labelCadastroNLotes: ':nth-child(10) > :nth-child(1) > .form-group > label',
    labelCadastroAreaTotal: ':nth-child(10) > :nth-child(2) > .form-group > label',
    labelCadastroResumoStatus:'.control-label',
    regiaoAdminContainer: '#select2-cd_regiao_admin-container',
    botaoReset: '#reset',
    orgaoProcessoSei: '#cd_orgao_processo_sei',
    nrProcessoSei:'#nr_processo_sei',
    anoProcessoSei: '#aa_processo_sei',
    tpEmpreendimentoContainer:'#select2-tp_empreendimento-container',
    dsEmpreendimento:'#ds_empreendimento',
    tpPrioridadeContainer: '#select2-tp_prioridade-container',
    pessoaTitularContainer:'#select2-cd_pessoa_titular-container',
    pessoaSuplenteContainer:'#select2-cd_pessoa_suplente-container',
    orgaoResponsavelContainer: '#select2-cd_orgao_responsavel-container',
    botaoSalvar: '#submit',
    modalConfirmar:'.modal-footer > .btn-primary',
    modalOk:'button.bootbox-accept',
    campoEmpreendimentoRA:':nth-child(1) > [whidth="350px"] > b',
    campoEmpreendimentoEmpreendimento:':nth-child(2) > [whidth="350px"] > b',
    campoEmpreendimentoEmpreendedorResponsavel:':nth-child(3) > [whidth="350px"] > b',
    campoEmpreendimentoTipo:':nth-child(4) > [whidth="350px"] > b',
    campoEmpreendimentoSEI:':nth-child(5) > [whidth="350px"] > b',
    campoEmpreendimentoPrioridade:':nth-child(6) > [whidth="350px"] > b',
    campoEmpreendimentoAreaTotal:':nth-child(7) > [whidth="350px"] > b',
    campoEmpreendimentoNLotes:':nth-child(8) > [whidth="350px"] > b',
    campoEmpreendimentoNURB:':nth-child(9) > [whidth="350px"] > b',
    campoEmpreendimentoNNGB:':nth-child(10) > [whidth="350px"] > b',
    campoEmpreendimentoNMDE:':nth-child(11) > [whidth="350px"] > b',
    campoEmpreendimentoTitular:':nth-child(12) > [whidth="350px"] > b',
    campoEmpreendimentoSuplente:':nth-child(13) > [whidth="350px"] > b',
    campoEmpreendimentoArquivado:':nth-child(14) > [whidth="350px"] > b',
    campoEmpreendimentoConcluido:':nth-child(15) > [whidth="350px"] > b',
    campoEmpreendimentoResumoStatus:':nth-child(16) > [whidth="350px"] > b',
    campoEmpreendimentoObservacao:':nth-child(17) > [whidth="350px"] > b',
    botaoVoltar:'[onclick="window.history.back()"]',
    botaoPesquisar:'#pesquisar',
    primeiroBotaoVisualizar:'a[title="Visualizar"]',
    botaoEmpreendimento:'#emprendimento-aba > .panel-footer > :nth-child(1) > a.btn',
    botaoDeletarEmpreendimento:'#btn-delete-empreendimento',
    modalDialogConfirmar:'.bootbox > .modal-dialog > .modal-content > .modal-footer > .btn-primary',




}
