export const ELEMENTS = {

    //login
    campoUsuario: ':nth-child(2) > .form-control',
    campoSenha: ':nth-child(3) > .form-control',
    botaoLogin: '.btn',
    abaEmpreendimento: '.sidebar-menu > :nth-child(2) > a > span',
    tituloPesquisar:'.box-title',
    labelRA:':nth-child(1) > :nth-child(1) > .form-group > label',
    labelEmpreendimento:'.col-md-6 > .form-group > label',
    labelTipo:':nth-child(1) > :nth-child(3) > .form-group > label',
    labelPrioridade:':nth-child(2) > :nth-child(1) > .form-group > label',
    labelTitular:':nth-child(2) > :nth-child(2) > .form-group > label',
    labelSuplente:':nth-child(2) > :nth-child(3) > .form-group > label',
    labelEmpreendedorResponsavel:'.col-md-8 > .form-group > label',
    labelArquivado:':nth-child(3) > :nth-child(2) > .form-group > label',
    labelConcluido:':nth-child(3) > :nth-child(3) > .form-group > label',
    labelPossuiExigencia:'.col-md-5 > .form-group > label',
    labelPossuiRequerimento:':nth-child(4) > .col-md-3 > .form-group > label',
    labelPossuiLicenca:':nth-child(4) > .col-md-4 > .form-group > label',
    ariaLabelRA:'.sorting_asc',
    ariaLabelEmpreendimento:'[aria-label="Empreendimento: Ordenar colunas de forma ascendente"]',
    ariaLabelTipo:'[aria-label="Tipo: Ordenar colunas de forma ascendente"]',
    ariaLabelEmpreendedorResponsavel:'[aria-label="Empreendedor Responsável: Ordenar colunas de forma ascendente"]',
    ariaLabelPrioridade:'[aria-label="Prioridade: Ordenar colunas de forma ascendente"]',
    ariaLabelTitular:'[aria-label="Titular: Ordenar colunas de forma ascendente"]',
    ariaLabelArquivado:'[aria-label="Arquivado: Ordenar colunas de forma ascendente"]',
    ariaLabelAcao:'[aria-label="Ação: Ordenar colunas de forma ascendente"]',
    seletorRA: ':nth-child(1) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    dropdownGLA: '.select2-results',
    seletorEmpreendimento:'.col-md-6 > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    seletorTipo:':nth-child(1) > :nth-child(3) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    seletorPrioridade:':nth-child(2) > :nth-child(1) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    seletorTitular:':nth-child(2) > :nth-child(2) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    seletorSuplente:':nth-child(2) > :nth-child(3) > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search > .select2-search__field',
    seletorEmpreendedorResponsavel:'.col-md-8 > .form-group > .select2-container > .selection > .select2-selection > .select2-selection__rendered > .select2-search',
    seletorArquivado:'#select2-fl_arquivado-container',
    seletorConcluido:'#select2-fl_concluido-container',
    seletorPossuiExigencia:'#select2-fl_exigencia_cumprir-container',
    seletorPossuiRequerimento:'.col-md-3 > .form-group > .select2-container > .selection > .select2-selection > #select2-fl_req_analise-container',
    seletorPossuiLicenca:'.col-md-4 > .form-group > .select2-container > .selection > .select2-selection > #select2-fl_req_analise-container',

}
