export const ELEMENTS = {

    campoUsuario: ':nth-child(2) > .form-control',
    campoSenha: ':nth-child(3) > .form-control',
    botaoLogin: '.btn',
    abaEmpreendimento:'.sidebar-menu > :nth-child(2) > a',
    campoSeletorEmpreendimento:'.col-md-6 > .form-group > .select2-container > .selection > .select2-selection',
    dropdwonGLA: '.select2-results',
    botaoPesquisar:'#pesquisar',
    botaoVisualizar:'a[title="Visualizar"]',
    abaRequerimentos:'.requerimentos-aba',
    campoDescricaoRequerimento:'#ds_requerimento',
    botaoLimpar:'.btn-toolbar > [type="button"]',
    linkEmpreendimento:'.text-block > a',
    botaoVoltar:'[onclick="window.history.back()"]',
    campoSeletorTpDemandaPermissao:'[id^="select2-tp_demanda_permissao-"][id$="-container"]',
    campoNumeroOficio:'#nr_oficio',
    campoAnoOficio:'#aa_oficio',
    campoSeletorOrgaoOficio:'[id^="select2-cd_orgao_oficio-"][id$="-container"]',
    campoDescricaoObservacaoDocOficio:'#ds_observacao_doc_oficio',
    campoSeletorPessoaTitular:'#select2-cd_pessoa_titular-container',
    campoSeletorOrgaoRequerimento:'[id^="select2-cd_orgao_requerimento-"][id$="-container"]',
    campoDataPublicacao:'#dt_publicacao',
    campoSeletorTpStatus:'[id^="select2-tp_status-"][id$="-container"]',
    campoOrgaoProcessoSei:'#cd_orgao_processo_sei',
    campoNumeroProcessoSei:'#nr_processo_sei',
    campoAnoProcessoSei:'#aa_processo_sei',
    campoReservaOrcamentaria:'#fl_reserva_orcamentaria',
    campoNrDocSeiDespacho:'#nr_doc_sei_despacho',
    botaoSalvar:'#submit',
    botaoContinuar: '.modal-footer > .btn-primary',
    botaoOk:'.modal-footer > .btn',
    abaRequerimento:':nth-child(7) > [href="#"]',
    abaConsultarRequerimento:'.menu-open > .treeview-menu > :nth-child(1) > a > span',
    botaoLimparCampoRequerimento:'[onclick="resetFieldsRequerimento()"]',
    seletorEmpreendimento:'#select2-cd_empreendimento-container',
    dropdownGLAOptions:'.select2-results__option',
    botaoPesquisarRequerimento: '#pesquisarRequerimento',
    botaoGerarRelatorioPDF:'#gerarRelatorioPDF',
    filtroRequerimento:'#table-requerimento_filter > label > .form-control',
    botaoLinkRequerimento:'#requerimento-aba > .panel-footer > :nth-child(1) > a.btn',
    botaoEditar:'a[title="Editar"]',
    botaoExcluir: 'a[title="Excluir"]',
    labelTipoRequerimento:'#requerimento-aba > :nth-child(3) > :nth-child(1) > .form-group > label',
    labelDemanda: '#requerimento-aba > :nth-child(3) > :nth-child(2) > .form-group > label',
    labelNumeroOficio:'#requerimento-aba > :nth-child(4) > :nth-child(1) > .form-group > label',
    labelAnoOficio:'#requerimento-aba > :nth-child(4) > :nth-child(2) > .form-group > label',
    labelEmitenteOficio:':nth-child(4) > :nth-child(3) > .form-group > label',
    labelNSeiDocRequerimento:':nth-child(4) > label',
    labelTitular: '#requerimento-aba > :nth-child(5) > :nth-child(1) > .form-group > label',
    labelSuplente: '#requerimento-aba > :nth-child(5) > :nth-child(2) > .form-group > label',
    labelDescricao:':nth-child(6) > .col-md-12 > .form-group > label',
    labelOrgaoRequerimento:':nth-child(7) > :nth-child(1) > .form-group > label',
    labelDataPublicacaoRequerimento: ':nth-child(7) > :nth-child(2) > .form-group > label',
    labelStatusRequerimento: ':nth-child(7) > :nth-child(3) > .form-group > label',
    labelSeiProcessoRequerimento: ':nth-child(4) > .form-group > label',
    labelReservaOrcamentaria: ':nth-child(8) > :nth-child(1) > .form-group > label',
    labelNDocSeiDespacho: ':nth-child(8) > :nth-child(2) > .form-group > label',
    labelStatusPagamento: ':nth-child(9) > :nth-child(1) > .form-group > label',
    labelPrazoMaximoAnalise:':nth-child(9) > :nth-child(2) > .form-group > label',
    labelEstudoServico: ':nth-child(9) > :nth-child(3) > .form-group > label',
    labelObservacaoSei:':nth-child(10) > :nth-child(1) > .form-group > label',
    labelObservacaoProcesso: ':nth-child(10) > :nth-child(2) > .form-group > label',
    labelPagamentosPrecoPublico: '.col-md-12 > label',
    labelSeiComprovantePagamento: '#table-pagamento > thead > tr > .sorting_asc',
    labelDataPagamento:'[aria-label="Data do Pagamento: Ordenar colunas de forma ascendente"]',
    labelValorPagamento:'[aria-label="Valor do Pagamento (R$): Ordenar colunas de forma ascendente"]',
    ariaLabelStatusPagamento:'[aria-label="Status do Pagamento: Ordenar colunas de forma ascendente"]',
    labelSeiCertidaoQuitacao:'[aria-label="SEI da Certidão de Quitação: Ordenar colunas de forma ascendente"]',
    labelDescricaoPagamento:'[aria-label="Descrição do Pagamento: Ordenar colunas de forma ascendente"]',
    labelAcao: '#table-pagamento > thead > tr > [aria-label="Ação: Ordenar colunas de forma ascendente"]',
    botaoCadastrarRequerimento:'#requerimento > .box > .box-body > .panel > .panel-body > .panel-footer > .btn-toolbar > .btn-success',
    cadastroControlLabelTipoRequerimento:':nth-child(3) > :nth-child(1) > .form-group > .control-label',
    cadastroControlLabelTipoDemandaPermissao: ':nth-child(3) > :nth-child(2) > .form-group > .control-label',
    cadastroControlLabelNumeroOficio: ':nth-child(4) > :nth-child(1) > .form-group > .control-label',
    cadastroControlLabelAnoOficio: ':nth-child(4) > :nth-child(2) > .form-group > .control-label',
    cadastroControlLabelEmitenteOficio: ':nth-child(4) > :nth-child(3) > .form-group > .control-label',
    cadastroControlLabelNSeiDocRequerimento: ':nth-child(4) > .form-group > .control-label',
    cadastroControlLabelTitular: ':nth-child(5) > :nth-child(1) > .form-group > label',
    cadastroControlLabelSuplente: ':nth-child(5) > :nth-child(2) > .form-group > label',
    cadastroControlLabelDescricao:':nth-child(6) > .col-md-12 > .form-group > .control-label',
    cadastroControlLabelOrgaoRequerimento:':nth-child(7) > :nth-child(1) > .form-group > .control-label',
    cadastroControlLabelDataPublicacaoRequerimento: ':nth-child(7) > :nth-child(2) > .form-group > .control-label',
    cadastroControlLabelLabelStatusRequerimento: ':nth-child(7) > :nth-child(3) > .form-group > .control-label',
    cadastroControlLabelSeiProcessoRequerimento: ':nth-child(7) > :nth-child(4) > :nth-child(1) > .form-group > label',
    cadastroControlLabelReservaOrcamentaria: ':nth-child(8) > .col-md-12 > .form-group > .control-label',
    cadastroControlLabelNDocSeiDespacho: '.col-md-4 > .form-group > .control-label',
    controlLabelRAConsultar: ':nth-child(1) > :nth-child(1) > .form-group > .control-label',
    controlLabelEmpreendimentoConsultar: ':nth-child(1) > :nth-child(2) > .form-group > .control-label',
    controlLabelDemandaConsultar: ':nth-child(1) > :nth-child(3) > .form-group > .control-label',
    controlLabelTipoRequerimentoConsultar: ':nth-child(2) > :nth-child(1) > .form-group > .control-label',
    controlLabelTipoDemandaPermissaoConsultar: ':nth-child(2) > :nth-child(2) > .form-group > label',
    controlLabelNumeroOficioConsultar: ':nth-child(3) > :nth-child(1) > .form-group > .control-label',
    controlLabelAnoOficioConsultar: ':nth-child(3) > :nth-child(2) > .form-group > .control-label',
    controlLabelEmitenteOficioConsultar: ':nth-child(3) > :nth-child(3) > .form-group > .control-label',
    controlLabelTitularConsultar: ':nth-child(4) > :nth-child(1) > .form-group > label',
    controlLabelSuplenteConsultar: ':nth-child(4) > :nth-child(2) > .form-group > label',
    controlLabelDescricaoConsultar: '.col-md-12 > .form-group > .control-label',
    controlLabelOrgaoRequerimentoConsultar: ':nth-child(6) > :nth-child(1) > .form-group > .control-label',
    controlLabelPeriodoDataPublicacaoRequerimentoConsultar: ':nth-child(2) > label',
    controlLabelStatusRequerimentoConsultar: ':nth-child(7) > :nth-child(1) > .form-group > .control-label',
    controlLabelEmpreendedorResponsavelConsultar: ':nth-child(7) > :nth-child(2) > .form-group > label',
    controlLabelPossuiReiteracoesConsultar: ':nth-child(7) > :nth-child(3) > .form-group > label',
    controlLabelReservaOrcamentariaDiplaConsultar: ':nth-child(8) > .col-md-6 > .form-group > .control-label',
    controlLabelStatusPagamentoConsultar: ':nth-child(8) > :nth-child(2) > .form-group > label',
    controlLabelPrazoMaximoAnaliseConsultar: ':nth-child(8) > :nth-child(3) > .form-group > label',
    controlLabelRaConsultar: '.sorting_asc',
    ariaLabelRequerimentoConsultar:'[aria-label="Requerimento: Ordenar colunas de forma ascendente"]',
    ariaLabelOrgaoConsultar:'[aria-label="Órgão: Ordenar colunas de forma ascendente"]',
    ariaLabelNOficioConsultar:'[aria-label="Nº Ofício: Ordenar colunas de forma ascendente"]',
    ariaLabelAnoConsultar:'[aria-label="Ano: Ordenar colunas de forma ascendente"]',
    ariaLabelEmitenteConsultar: '[aria-label="Emitente: Ordenar colunas de forma ascendente"]',
    ariaLabelDataPublicacaoConsultar:'[aria-label="Data de Publicação: Ordenar colunas de forma ascendente"]',
    ariaLabelAcaoConsultar:'[aria-label="Ação: Ordenar colunas de forma ascendente"]',
    ariaLabelEmpreendimentoConsultar:'[aria-label="Empreendimento: Ordenar colunas de forma ascendente"]',
    controlLabelTipoRequerimentoEditar:':nth-child(3) > :nth-child(1) > .form-group > .control-label',
    controlLabelDemandaEditar:':nth-child(3) > :nth-child(2) > .form-group > .control-label',
    controlLabelNumeroOficioEditar:':nth-child(4) > :nth-child(1) > .form-group > .control-label',
    controlLabelAnoOficioEditar:':nth-child(4) > :nth-child(2) > .form-group > .control-label',
    controlLabelEmitenteOficioEditar:':nth-child(4) > :nth-child(3) > .form-group > .control-label',
    controlLabelNSeiDocRequerimentoEditar:':nth-child(4) > .form-group > .control-label',
    controlLabelTitularEditar:':nth-child(5) > :nth-child(1) > .form-group > label',
    controlLabelSuplenteEditar:':nth-child(5) > :nth-child(2) > .form-group > label',
    controlLabelDescricaoEditar:':nth-child(6) > .col-md-12 > .form-group > .control-label',
    controlLabelOrgaoRequerimentoEditar:':nth-child(7) > :nth-child(1) > .form-group > .control-label',
    controlLabelDataPublicacaoRequerimentoEditar:':nth-child(7) > :nth-child(2) > .form-group > .control-label',
    controlLabelStatusRequerimentoEditar:':nth-child(7) > :nth-child(3) > .form-group > .control-label',
    controlLabelSeiProcessoRequerimentoEditar:':nth-child(7) > :nth-child(4) > :nth-child(1) > .form-group > label',
    controlLabelReservaOrcamentariaDiplaEditar:':nth-child(8) > .col-md-12 > .form-group > .control-label',
    controlLabelNDocSeiDespachoEditar:'.col-md-4 > .form-group > .control-label',
    adicionarEmpreendimento:'#add_empreendimento',
    caixaAviso:'.bootbox-body',
}