export const ELEMENTS = {

    //login
    campoUsuario: ':nth-child(2) > .form-control',
    campoSenha: ':nth-child(3) > .form-control',
    botaoLogin: '.btn',
    abaEmpreendimento:'.sidebar-menu > :nth-child(2) > a',
    campoSeletorEmpreendimento:'.col-md-6 > .form-group > .select2-container > .selection > .select2-selection',
    dropdwonGLA: '.select2-results',
    botaoPesquisar:'#pesquisar',
    botaoVisualizar:'a[title="Visualizar"]',
    abaRequerimentos:'.requerimentos-aba',
    campoDescricaoRequerimento:'#ds_requerimento',
    botaoLimpar:'.btn-toolbar > [type="button"]',
    linkEmpreendimento:'.text-block > a',
    botaoVoltar:'[onclick="window.history.back()"]',
    campoSeletorTpDemandaPermissao:'[id^="select2-tp_demanda_permissao-"][id$="-container"]',
    campoNumeroOficio:'#nr_oficio',
    campoAnoOficio:'#aa_oficio',
    campoSeletorOrgaoOficio:'[id^="select2-cd_orgao_oficio-"][id$="-container"]',
    campoDescricaoObservacaoDocOficio:'#ds_observacao_doc_oficio',
    campoSeletorPessoaTitular:'#select2-cd_pessoa_titular-container',
    campoSeletorOrgaoRequerimento:'[id^="select2-cd_orgao_requerimento-"][id$="-container"]',
    campoDataPublicacao:'#dt_publicacao',
    campoSeletorTpStatus:'[id^="select2-tp_status-"][id$="-container"]',
    campoOrgaoProcessoSei:'#cd_orgao_processo_sei',
    campoNumeroProcessoSei:'#nr_processo_sei',
    campoAnoProcessoSei:'#aa_processo_sei',
    campoReservaOrcamentaria:'#fl_reserva_orcamentaria',
    campoNrDocSeiDespacho:'#nr_doc_sei_despacho',
    botaoSalvar:'#submit',
    botaoContinuar: '.modal-footer > .btn-primary',
    botaoOk:'.modal-footer > .btn',
    abaRequerimento:':nth-child(7) > [href="#"]',
    abaConsultarRequerimento:'.menu-open > .treeview-menu > :nth-child(1) > a > span',
    botaoLimparCampoRequerimento:'[onclick="resetFieldsRequerimento()"]',
    seletorEmpreendimento:'#select2-cd_empreendimento-container',
    dropdownGLAOptions:'.select2-results__option',
    botaoPesquisarRequerimento: '#pesquisarRequerimento',
    botaoGerarRelatorioPDF:'#gerarRelatorioPDF',
    filtroRequerimento:'#table-requerimento_filter > label > .form-control',
    botaoLinkRequerimento:'#requerimento-aba > .panel-footer > :nth-child(1) > a.btn',
    botaoEditar:'a[title="Editar"]',
    botaoExcluir: 'a[title="Excluir"]',
    labelTipoRequerimento:'#requerimento-aba > :nth-child(3) > :nth-child(1) > .form-group > label',
    labelDemanda: '#requerimento-aba > :nth-child(3) > :nth-child(2) > .form-group > label',
    labelNumeroOficio:'#requerimento-aba > :nth-child(4) > :nth-child(1) > .form-group > label',
    labelAnoOficio:'#requerimento-aba > :nth-child(4) > :nth-child(2) > .form-group > label',
    labelEmitenteOficio:':nth-child(4) > :nth-child(3) > .form-group > label',
    labelNSeiDocRequerimento:':nth-child(4) > label',

}