export const ELEMENTS = {

    campoUsuario: ':nth-child(2) > .form-control',
    campoSenha: ':nth-child(3) > .form-control',
    botaoLogin: '.btn',
    abaRequerimento: ':nth-child(7) > [href="#"]',
    abaConsultarReiteracoes: '.menu-open > .treeview-menu > :nth-child(2) > a > span',
    botaoCadastrarReiteracoes: '.btn-success',
    seletorRegiaoAdm: '#select2-regiao_adm-container',
    dropdownGLA:'.select2-results',
    seletorEmpreendimentoContainer: '#select2-combo_empreendimento-container',
    seletorTipoRequerimentoContainer:'#select2-combo_tipo_requerimento-container',
    seletorRequerimentoContainer:'#select2-combo_requerimento-container',
    botaoAdicionar: '#btn_adicionar',
    botaoSalvar: '#submit',
    modalConfirmar:'.modal-footer > .btn-primary',
    seletorRegiaoAdminContainer: '#select2-cd_regiao_admin-container',
    seletorTpRequerimentoContainer: '#select2-tp_requerimento-container',
    botaoPesquisar: '#pesquisar',
    filtroReiteracao:'#table-reiteracao_filter > label > .form-control',
    primeiroBotaoVisualizar: 'a[title="Visualizar"]',
    primeiroBotaoEditar:'a[title="Editar"]',
    botaoEditar: '.sidebar-toggle',
    modalSalvar:'.modal-footer > .btn-primary',
    modalOk:'.modal-footer > .btn',
    primeiroBotaoExcluir:'a[title="Excluir"]',
    labelCadastrarRA:':nth-child(1) > .form-group > .control-label',
    labelCadastrarEmpreendimento:':nth-child(2) > .form-group > .control-label',
    labelCadastrarTipoRequerimento:':nth-child(3) > .form-group > .control-label',
    labelCadastrarRequerimentos:'.col-md-12 > :nth-child(1) > .control-label',
    labelPesquisarReiteracaoRA:':nth-child(1) > .form-group > .control-label',
    labelPesquisarReiteracaoEmpreendimento:':nth-child(2) > .form-group > .control-label',
    labelPesquisarReiteracaoTipoRequerimento:':nth-child(3) > .form-group > .control-label',
    labelPesquisarReiteracaoCodigoReiteracao:'.sorting_asc',
    ariaLabelPesquisarReiteracaoEmpreendimento:'[aria-label="Empreendimento: Ordenar colunas de forma ascendente"]',
    ariaLabelPesquisarReiteracaoTipoRequerimento:'[aria-label="Tipo Requerimento: Ordenar colunas de forma ascendente"]',
    ariaLabelPesquisarReiteracaoDataPubReq:'[aria-label="Data Publicação/Requerimento: Ordenar colunas de forma ascendente"]',
    ariaLabelPesquisarReiteracaoAcao:'[aria-label="Ação: Ordenar colunas de forma ascendente"]',
    labelEditarRA:'.col-md-4 > .form-group > .control-label',
    labelEditarEmpreendimento:'.col-md-5 > .form-group > .control-label',
    labelEditarTipoRequerimento:'.col-md-3 > .form-group > .control-label',
    labelEditarRequerimentos:'.col-md-12 > :nth-child(1) > .control-label',
    labelEditarRequerimentosReiterados:'thead > tr > :nth-child(1)',
    widthRequerimentosReiterados:'[width="50%"]',
    widthDataPublicacao:'[width="20%"]',
    widthAcaoRequerimento:'[width="30%"]',
    botaoVoltar:'[onclick="window.history.back()"]',
}
